 SELECT '-1' AS JOB_ID, 
 'NULL' AS PROCESS_NAME, 
 NULL AS FUNCTIONAL_AREA_CODE, 
 NULL AS TABLE_NAME, 
 NULL AS TABLE_TYPE, 
 NULL AS ERROR_TIME, 
 NULL AS ERROR_CODE, 
 NULL AS RESERVED1, 
 NULL AS ERROR_RECORD_ID, 
 NULL AS ERROR_STATUS, 
 NULL AS ERROR_SUB_STATUS, 
 '$VAR_SYS_SRC_TYPE_CODE$' AS SOURCE_TYPE_CODE

