 SELECT  "DW_WRKFRC_SUPERVISOR_SNAPSHOT_F" AS OBJECT_NAME	, 
 	DATE('2015-01-01') AS LAST_LOAD_DATE	
UNION ALL
 SELECT  "DW_WRKFRC_ASG_SNAPSHOT_F" AS OBJECT_NAME	, 
 	DATE('2015-01-01') AS LAST_LOAD_DATE

