 SELECT  PARAMTABLE.PARAMID AS PARAMETER_CODE , 
  PARAMTABLE.VALUES_VALUEID AS PARAMETER_VALUE 
 FROM {{ ref('DW_CONTENT_PARAM_CONFIG_PARAMTABLE_I') }} PARAMTABLE
 WHERE  PARAMTABLE.PARAMID NOT IN ('PARAM_HCM_WORKFORCE_PERFORMANCE_BAND_ID','PARAM_HCM_WORKFORCE_POTENTIAL_BAND_ID','PARAM_HCM_WORKFORCE_TENURE_BAND_ID','PARAM_HCM_WORKFORCE_WORKER_AGE_BAND_ID')
