 SELECT  ASG_SV_F.MANAGER_ASSIGNMENT_ID AS MANAGER_ASSIGNMENT_ID , 
  ASG_SV_F.DATE_FROM AS DATE_FROM , 
  TO_CHAR(ASG_SV_F.MANAGER_ASSIGNMENT_ID)||'~'|| TO_CHAR((ASG_SV_F.DATE_FROM),'YYYYMMDD') AS SOURCE_RECORD_ID , 
  ASG_SV_F.DATE_TO AS DATE_TO , 
  ASG_SV_F.PRIMARY_FLAG AS PRIMARY_FLAG , 
  ASG_SV_F.MANAGER_TYPE AS MANAGER_TYPE , 
  ASG_SV_F.MANAGER_ID AS MANAGER_ID , 
  ASG_SV_F.MANAGER_FLAG AS MANAGER_FLAG 
 FROM {{ ref('DW_WRKFRC_ASG_SUPERVISOR_F') }} ASG_SV_F

