 SELECT  APVO.ACTIONID AS ACTION_ID, 
 APVO.ACTIONID AS SOURCE_RECORD_ID , 
  APVO.ACTIONSPEOACTIONCODE AS ACTION_CODE, 
  APVO.ACTIONSPEOACTIONTYPEID AS ACTION_TYPE_ID, 
  APVO.ACTIONSPEOACTIONTYPECODE AS ACTION_TYPE_CODE, 
  APVO.ACTIONSPEOACTINFORMATION2 AS TERMINATION_TYPE, 
  APVO.ACTIONSPEOACTINFORMATION1 AS REORGANIZATION_FLAG
 FROM {{ ref('stg_h_actionam_actionspvo') }} APVO

