 SELECT ARPVO.ACTIONREASONID AS ACTION_REASON_ID, 
 ARPVO.ACTIONREASONID AS SOURCE_RECORD_ID , 
 ARPVO.ACTIONREASONSPEOACTIONREASONCODE AS ACTION_REASON_CODE
 FROM {{ ref('stg_h_actionam_actionreasonspvo') }} ARPVO

