 SELECT 	CNTNTTYP.CONTENTTYPEBPEOCONTENTTYPEID AS CONTENT_TYPE_ID		, 
 	CNTNTTYP.CONTENTTYPEBPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID	, 
 	TO_CHAR(CNTNTTYP.CONTENTTYPEBPEOCONTENTTYPEID)||'~'||TO_CHAR(CNTNTTYP.CONTENTTYPEBPEOBUSINESSGROUPID) AS SOURCE_RECORD_ID	, 
 	CNTNTTYP.CONTENTTYPEBPEOCONTEXTNAME AS CONTEXT_NAME		
 FROM {{ ref('stg_h_hcmprofilecontentlibraryam_contenttypepvo') }} CNTNTTYP

