 SELECT  CNT.CONTENTITEMBPEOCONTENTITEMID AS CONTENT_ITEM_ID    , 
  CNT.CONTENTITEMBPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID  , 
  TO_CHAR(CNT.CONTENTITEMBPEOCONTENTITEMID) ||'~'|| TO_CHAR(CNT.CONTENTITEMBPEOBUSINESSGROUPID) AS SOURCE_RECORD_ID   , 
  CNT.CONTENTITEMBPEOCONTENTTYPEID AS CONTENT_TYPE_ID    , 
  CNT.CONTENTITEMBPEOCONTENTITEMCODE AS CONTENT_ITEM_CODE  , 
  CNT.CONTENTITEMBPEODATEFROM AS DATE_FROM          , 
  CNT.CONTENTITEMBPEODATETO AS DATE_TO            
 FROM {{ ref('stg_h_hcmprofilecontentlibraryam_contentitempvo') }} CNT

