 SELECT  GOALPPVO1.MEASUREMENTPEOMEASUREMENTID AS MEASUREMENT_ID , 
  TO_CHAR(GOALPPVO1.MEASUREMENTPEOMEASUREMENTID) AS SOURCE_RECORD_ID , 
  GOALPPVO1.MEASUREMENTPEOGOALID3_1 AS GOAL_ID , 
  GOALPPVO1.MEASUREMENTPEOBUSINESSGROUPID2_1 AS BUSINESS_GROUP_ID , 
  GOALPPVO1.MEASUREMENTPEOMEASUREMENTNAME AS MEASUREMENT_NAME , 
  GOALPPVO1.MEASUREMENTPEOACHIEVEDWEIGHT AS ACHIEVED_WEIGHT , 
  GOALPPVO1.MEASUREMENTPEOSTARTDATE1_1 AS START_DATE , 
  GOALPPVO1.MEASUREMENTPEOENDDATE AS END_DATE , 
  GOALPPVO1.MEASUREMENTPEOMEASURETYPECODE AS MEASUREMENT_TYPE_CODE , 
  GOALPPVO1.MEASUREMENTPEOTARGETTYPE AS TARGET_TYPE , 
  GOALPPVO1.MEASUREMENTPEOTARGETPERCENTAGE AS TARGET_PERCENTAGE , 
  GOALPPVO1.MEASUREMENTPEOTARGETVALUE AS TARGET_VALUE , 
  GOALPPVO1.MEASUREMENTPEOACTUALVALUE AS ACTUAL_VALUE , 
  GOALPPVO1.MEASUREMENTPEOMAXTARGET AS MAX_TARGET , 
  GOALPPVO1.MEASUREMENTPEOMINTARGET AS MIN_TARGET , 
  GOALPPVO1.MEASUREMENTPEOUOMCODE AS UOM_CODE , 
  GOALPPVO1.MEASUREMENTPEODISPLAYSEQUENCE AS DISPLAY_SEQUENCE 
 FROM {{ ref('stg_h_hcmgoalcoream_goalppvo1') }} GoalPPVO1
 WHERE  GOALPPVO1.MEASUREMENTPEOMEASUREMENTID IS NOT NULL
