 SELECT RATEPVO.RATEID AS RATE_ID, 
 RATEPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 RATEPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 CAST(RATEPVO.RATEID AS STRING) ||'~'|| FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', RATEPVO.EFFECTIVESTARTDATE)) ||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', RATEPVO.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID, 
 RATEPVO.RATEPEORATETYPE AS RATE_TYPE, 
 RATEPVO.RATEPEORATEOBJECTTYPE AS RATE_OBJECT_TYPE, 
 RATEPVO.RATEPEORATEUOM AS RATE_UOM, 
 RATEPVO.RATEPEORATEFREQUENCY AS RATE_FREQUENCY, 
 RATEPVO.RATEPEOCURRENCYCODE AS CURRENCY_CODE, 
 COALESCE(RATEPVO.RATEPEOLEGISLATIONCODE,'~NOVALUE~') AS LEGISLATION_CODE, 
 RATEPVO.RATEPEOACTIVESTATUS AS ACTIVE_STATUS, 
 RATEPVO.RATEPEOANNUALIZATIONFACTOR AS ANNUALIZATION_FACTOR
 FROM {{ ref('stg_h_gradeam_ratepvo') }} RATEPVO
 WHERE RATEPVO.RATEPEORATETYPE='SALARY'
