 SELECT  GOALSET.GOALPLANSETID AS GOAL_PLAN_SET_ID , 
  TO_CHAR(GOALSET.GOALPLANSETID) AS SOURCE_RECORD_ID , 
  GOALSET.GOALPLANSETBPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID , 
  GOALSET.GOALPLANSETBPEOENDDATE AS END_DATE , 
  GOALSET.GOALPLANSETBPEOGOALPLANSETACTIVEFLAG AS GOAL_PLAN_SET_ACTIVE_FLAG , 
  GOALSET.GOALPLANSETBPEOSTARTDATE AS START_DATE 
 FROM {{ ref('stg_h_hcmgoalcoream_goalplansetpvo') }} GOALSET

