 SELECT  GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALID AS GOAL_PLAN_GOAL_ID , 
  TO_CHAR(GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALID) AS SOURCE_RECORD_ID , 
  GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOGOALPLANID AS GOAL_PLAN_ID , 
  GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOGOALID AS GOAL_ID , 
  GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOWEIGHTING AS Weighting , 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOPRIORITYCODE AS Priority_Code, 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOGOALPLANSETID1 AS GOAL_PLAN_SET_ID, 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOEFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOEFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALPEOREVIEWPERIODID AS REVIEW_PERIOD_ID, 
 GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPEOASSIGNMENTID AS ASSIGNMENT_ID
 FROM {{ ref('stg_h_hcmgoalcoream_goalstatusoverviewpvo.goalplangoal') }} GoalStatusOverviewPVOGoalPlanGoal
 WHERE  GOALSTATUSOVERVIEWPVOGOALPLANGOAL.GOALPLANGOALID IS NOT NULL
