 SELECT  ALIGNMENT.GOALALIGNMENTPEOGOALALIGNMENTID AS GOAL_ALIGNMENT_ID , 
  TO_CHAR(ALIGNMENT.GOALALIGNMENTPEOGOALALIGNMENTID) AS SOURCE_RECORD_ID , 
  ALIGNMENT.GOALALIGNMENTPEOGOALID1 AS GOAL_ID , 
  ALIGNMENT.GOALALIGNMENTPEOALIGNEDGOALID AS ALIGNED_GOAL_ID , 
  ALIGNMENT.GOALPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID 
 FROM {{ ref('stg_h_hcmgoalcoream_goalppvo1.alignment') }} ALIGNMENT

