 SELECT  PLANASSIGNMENT.GOALPLANASSIGNMENTID AS GOAL_PLAN_ASSIGNMENT_ID , 
  TO_CHAR(PLANASSIGNMENT.GOALPLANASSIGNMENTID) AS SOURCE_RECORD_ID , 
  PLANASSIGNMENT.ASSIGNMENTID AS ASSIGNMENT_ID , 
  PLANASSIGNMENT.GOALPLANENDDATE AS GOAL_PLAN_END_DATE , 
  PLANASSIGNMENT.GOALPLANID AS GOAL_PLAN_ID , 
  PLANASSIGNMENT.GOALPLANSETENDDATE AS GOAL_PLAN_SET_END_DATE , 
  PLANASSIGNMENT.GOALPLANSETID AS GOAL_PLAN_SET_ID , 
  PLANASSIGNMENT.GOALPLANSETSTARTDATE AS GOAL_PLAN_SET_START_DATE , 
  PLANASSIGNMENT.GOALPLANSTARTDATE AS GOAL_PLAN_START_DATE , 
  PLANASSIGNMENT.ORGANIZATIONID AS ORGANIZATION_ID , 
  PLANASSIGNMENT.PERSONID AS PERSON_ID , 
  PLANASSIGNMENT.STATUS AS STATUS , 
  PLANASSIGNMENT.WEIGHTING AS WEIGHTING , 
  PLANASSIGNMENT.REVIEWPERIODIDATTR AS REVIEW_PERIOD_ID 
 FROM {{ ref('stg_h_hcmgoalcoream_goalplanassignmentfactp1') }} PLANASSIGNMENT

