 SELECT RATEVALUEPVO.RATEVALUEID AS RATE_VALUE_ID, 
 RATEVALUEPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 RATEVALUEPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 CAST(RATEVALUEPVO.RATEVALUEID AS STRING) ||'~'|| FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', RATEVALUEPVO.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', RATEVALUEPVO.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID, 
 RATEVALUEPVO.RATEVALUEPEORATEID AS RATE_ID, 
 RATEVALUEPVO.RATEVALUEPEORATEOBJECTTYPE AS RATE_OBJECT_TYPE, 
 RATEVALUEPVO.RATEVALUEPEORATEOBJECTID AS RATE_OBJECT_ID, 
 RATEVALUEPVO.RATEVALUEPEOMINIMUM AS MINIMUM, 
 RATEVALUEPVO.RATEVALUEPEOMAXIMUM AS MAXIMUM, 
 RATEVALUEPVO.RATEVALUEPEOMIDVALUE AS MID_VALUE, 
 COALESCE(RATEVALUEPVO.RATEVALUEPEOLEGISLATIONCODE,'~NOVALUE~') AS LEGISLATION_CODE
 FROM {{ ref('stg_h_gradeam_ratevaluepvo') }} RATEVALUEPVO
 WHERE RATEVALUEPVO.RATEVALUEPEORATEOBJECTTYPE IN ('GRADE','G','STEP')
