 SELECT GRDRATE.RATE_ID AS RATE_ID, 
 GRDRATE.SOURCE_RECORD_ID AS SOURCE_RECORD_ID, 
 GRDRATE.RATE_TYPE AS RATE_TYPE, 
 GRDRATE.RATE_OBJECT_TYPE AS RATE_OBJECT_TYPE, 
 GRDRATE.RATE_UOM AS RATE_UOM, 
 GRDRATE.RATE_FREQUENCY AS RATE_FREQUENCY, 
 GRDRATE.CURRENCY_CODE AS CURRENCY_CODE, 
 GRDRATE.LEGISLATION_CODE AS LEGISLATION_CODE, 
 GRDRATE.ACTIVE_STATUS AS ACTIVE_STATUS, 
 GRDRATE.ANNUALIZATION_FACTOR AS ANNUALIZATION_FACTOR
 FROM {{ ref('DW_GRADE_RATE_D') }} GRDRATE
 WHERE  TRUNC(SYSDATE) BETWEEN GRDRATE.EFFECTIVE_START_DATE AND GRDRATE.EFFECTIVE_END_DATE
