 SELECT RATEPVO.RATEID AS RATE_ID, 
 RATEPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 RATEPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 TO_CHAR(RATEPVO.RATEID) ||'~'|| TO_CHAR(RATEPVO.EFFECTIVESTARTDATE,'YYYYMMDD') ||'~'||TO_CHAR(RATEPVO.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID, 
 RATEPVO.RATEPEORATETYPE AS RATE_TYPE, 
 RATEPVO.RATEPEORATEOBJECTTYPE AS RATE_OBJECT_TYPE, 
 RATEPVO.RATEPEORATEUOM AS RATE_UOM, 
 RATEPVO.RATEPEORATEFREQUENCY AS RATE_FREQUENCY, 
 RATEPVO.RATEPEOCURRENCYCODE AS CURRENCY_CODE, 
 COALESCE(RATEPVO.RATEPEOLEGISLATIONCODE,'~NOVALUE~') AS LEGISLATION_CODE, 
 RATEPVO.RATEPEOACTIVESTATUS AS ACTIVE_STATUS, 
 RATEPVO.RATEPEOANNUALIZATIONFACTOR AS ANNUALIZATION_FACTOR
 FROM {{ ref('stg_h_gradeam_ratepvo') }} RatePVO
 WHERE RATEPVO.RATEPEORATETYPE='SALARY'
