 SELECT  DISTINCT  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANID AS GOAL_PLAN_ID , 
  TO_CHAR(GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANID) AS SOURCE_RECORD_ID , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANTYPECODE AS GOAL_PLAN_TYPE_CODE , 
  GOALSTATUSOVERVIEWPVO.STARTDATE1 AS GOAL_PLAN_START_DATE , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOENDDATE AS GOAL_PLAN_END_DATE , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOPREVIOUSGOALPLANID AS PREV_GOAL_PLAN_ID , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOENFORCEGOALWEIGHTFLAG AS ENFORCE_GOAL_WEIGHT_FLAG , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALACCESSLEVELCODE AS GOAL_ACCESS_LEVEL_CODE , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANACTIVEFLAG AS GOAL_PLAN_ACTIVE_FLAG , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALSUBTYPECODE AS GOAL_SUBTYPE_CODE , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOINCLUDEINPERFDOCFLAG AS INCLUDE_IN_PERFDOC_FLAG , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOENABLEWEIGHTINGFLAG AS ENABLE_WEIGHTING_FLAG , 
  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOREVIEWPERIODID AS REVIEW_PERIOD_ID , 
 PERFORMANCEGOALPLANPVO.GOALPLANBPEOPRIMGOALPLANFLAG AS PRIMARY_GOAL_PLAN_FLAG
 FROM  {{ ref('stg_h_hcmgoalcoream_goalstatusoverviewpvo') }} GoalStatusOverviewPVO INNER JOIN {{ ref('stg_h_hcmgoalcoream_performancegoalplanpvo') }} PerformanceGoalPlanPVO  ON GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANID	= PERFORMANCEGOALPLANPVO.GOALPLANID AND GOALSTATUSOVERVIEWPVO.GOALPLANBPEOBUSINESSGROUPID=PERFORMANCEGOALPLANPVO.GOALPLANBPEOBUSINESSGROUPID
 WHERE  GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANID IS NOT NULL AND GOALSTATUSOVERVIEWPVO.GOALPLANBPEOGOALPLANTYPECODE IN ('ORA_HRG_WORKER','ORA_HRG_ORGANIZATION')
