 SELECT JOB.JOB_ID AS JOB_ID, 
 JOB.SOURCE_RECORD_ID AS SOURCE_RECORD_ID, 
 JOB.JOB_CODE AS JOB_CODE, 
 JOB.JOB_FAMILY_ID AS JOB_FAMILY_ID, 
 JOB.ACTIVE_STATUS AS ACTIVE_STATUS, 
 JOB.MANAGER_LEVEL AS MANAGER_LEVEL, 
 JOB.MED_CHECKUP_REQ AS MED_CHECKUP_REQ, 
 JOB.JOB_FUNCTION_CODE AS JOB_FUNCTION_CODE, 
 JOB.PROGRESSION_JOB_ID AS PROGRESSION_JOB_ID
 FROM {{ ref('DW_JOB_D') }} JOB
WHERE  CURRENT_DATE() BETWEEN PARSE_DATE('%Y-%m-%d',JOB.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',JOB.EFFECTIVE_END_DATE)
