 SELECT JOBFAMILYPVO.JOBFAMILYID AS JOB_FAMILY_ID, 
 JOBFAMILYPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 JOBFAMILYPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 TO_CHAR(JOBFAMILYPVO.JOBFAMILYID)||'~'|| TO_CHAR(JOBFAMILYPVO.EFFECTIVESTARTDATE,'YYYYMMDD') ||'~'||TO_CHAR(JOBFAMILYPVO.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID, 
 JOBFAMILYPVO.JOBFAMILYPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID, 
 JOBFAMILYPVO.JOBFAMILYPEOACTIVESTATUS AS ACTIVE_STATUS, 
 JOBFAMILYPVO.JOBFAMILYCODE AS JOB_FAMILY_CODE
 FROM {{ ref('stg_h_jobam_jobfamilypvo') }} JobFamilyPVO

