 SELECT JOBFM.JOB_FAMILY_ID AS JOB_FAMILY_ID, 
 JOBFM.SOURCE_RECORD_ID AS SOURCE_RECORD_ID, 
 JOBFM.BUSINESS_GROUP_ID AS BUSINESS_GROUP_ID, 
 JOBFM.ACTIVE_STATUS AS ACTIVE_STATUS, 
 JOBFM.JOB_FAMILY_CODE AS JOB_FAMILY_CODE
 FROM {{ ref('DW_JOB_FAMILY_D') }} JOBFM
 WHERE  CURRENT_DATE() BETWEEN PARSE_DATE('%Y-%m-%d',JOBFM.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',JOBFM.EFFECTIVE_END_DATE)
