 SELECT JOBPVO.JOBID AS JOB_ID, 
 JOBPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 JOBPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 CAST(JOBPVO.JOBID AS STRING) ||'~'|| FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', JOBPVO.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', JOBPVO.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID, 
 JOBPVO.JOBPEOJOBCODE AS JOB_CODE, 
 COALESCE(JOBPVO.JOBPEOJOBFAMILYID,-99999) AS JOB_FAMILY_ID, 
 JOBPVO.JOBPEOACTIVESTATUS AS ACTIVE_STATUS, 
 COALESCE(CAST(JOBPVO.JOBPEOMANAGERLEVEL AS STRING),'~NOVALUE~') AS MANAGER_LEVEL, 
 COALESCE(CAST(JOBPVO.JOBPEOMEDCHECKUPREQ AS STRING),'~NOVALUE~') AS MED_CHECKUP_REQ, 
 COALESCE(JOBPVO.JOBPEOJOBFUNCTIONCODE,'~NOVALUE~') AS JOB_FUNCTION_CODE, 
 COALESCE(JOBPVO.JOBPEOPROGRESSIONJOBID,-99999) AS PROGRESSION_JOB_ID
 FROM {{ ref('stg_h_jobam_jobpvo') }} JOBPVO

