 SELECT MHDN.PERSONID AS PERSON_ID, 
 MHDN.ASSIGNMENTID AS ASSIGNMENT_ID, 
 MHDN.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 MHDN.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 MHDN.MANAGERTYPE AS MANAGER_TYPE, 
 MHDN.MANAGERID AS MANAGER_ID, 
 MHDN.MANAGERASSIGNMENTID AS MANAGER_ASSIGNMENT_ID, 
 MHDN.MANAGERLEVEL AS MANAGER_DISTANCE, 
 MHDN.BUSINESSGROUPID AS BUSINESS_GROUP_ID, 
 MHDN.PERSONID||'~'||MHDN.ASSIGNMENTID||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', MHDN.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', MHDN.EFFECTIVEENDDATE))||'~'|| MHDN.MANAGERTYPE||'~'||MHDN.MANAGERID||'~'||MHDN.MANAGERASSIGNMENTID||'~'||MHDN.MANAGERLEVEL||'~'||MHDN.BUSINESSGROUPID AS SOURCE_RECORD_ID, 
 MHDN.PRIMARYASSIGNMENTFLAG AS PRIMARY_ASSIGNMENT_FLAG, 
 MHDN.PRIMARYMANAGERFLAG AS PRIMARY_MANAGER_FLAG, 
 CASE WHEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') > PARSE_DATE('%Y-%m-%d', MHDN.EFFECTIVESTARTDATE ) THEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') ELSE PARSE_DATE('%Y-%m-%d', MHDN.EFFECTIVESTARTDATE) END AS DW_DATE_FROM, 
 MHDN.EFFECTIVEENDDATE AS DW_DATE_TO, 
  CASE WHEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') > PARSE_DATE('%Y-%m-%d', MHDN.EFFECTIVESTARTDATE)  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM {{ ref('stg_h_managerhierarchyam_managerhierarchydnpvolinemanager') }} MHDN

