 SELECT MHDN.PERSONID AS PERSON_ID, 
 MHDN.ASSIGNMENTID AS ASSIGNMENT_ID, 
 MHDN.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 MHDN.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 MHDN.MANAGERTYPE AS MANAGER_TYPE, 
 MHDN.MANAGERID AS MANAGER_ID, 
 MHDN.MANAGERASSIGNMENTID AS MANAGER_ASSIGNMENT_ID, 
 MHDN.MANAGERLEVEL AS MANAGER_DISTANCE, 
 MHDN.BUSINESSGROUPID AS BUSINESS_GROUP_ID, 
 MHDN.PERSONID||'~'||MHDN.ASSIGNMENTID||'~'||TO_CHAR(MHDN.EFFECTIVESTARTDATE,'YYYYMMDD')||'~'||TO_CHAR(MHDN.EFFECTIVEENDDATE,'YYYYMMDD')||'~'|| MHDN.MANAGERTYPE||'~'||MHDN.MANAGERID||'~'||MHDN.MANAGERASSIGNMENTID||'~'||MHDN.MANAGERLEVEL||'~'||MHDN.BUSINESSGROUPID AS SOURCE_RECORD_ID, 
 MHDN.PRIMARYASSIGNMENTFLAG AS PRIMARY_ASSIGNMENT_FLAG, 
 MHDN.PRIMARYMANAGERFLAG AS PRIMARY_MANAGER_FLAG, 
 GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),MHDN.EFFECTIVESTARTDATE) AS DW_DATE_FROM, 
 MHDN.EFFECTIVEENDDATE AS DW_DATE_TO, 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') > MHDN.EFFECTIVESTARTDATE  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM {{ ref('stg_h_managerhierarchyam_managerhierarchydnpvolinemanager') }} MHDN

