 SELECT  DNDH.PERSON_ID AS PERSON_ID , 
  DNDH.ASSIGNMENT_ID AS ASSIGNMENT_ID , 
  DNDH.MANAGER_TYPE AS MANAGER_TYPE , 
  DNDH.MANAGER_ID AS MANAGER_ID , 
  DNDH.MANAGER_ASSIGNMENT_ID AS MANAGER_ASSIGNMENT_ID , 
  DNDH.MANAGER_DISTANCE AS MANAGER_DISTANCE , 
  DNDH.BUSINESS_GROUP_ID AS BUSINESS_GROUP_ID , 
  DNDH.SOURCE_RECORD_ID AS SOURCE_RECORD_ID , 
  DNDH.PRIMARY_ASSIGNMENT_FLAG AS PRIMARY_ASSIGNMENT_FLAG , 
  DNDH.PRIMARY_MANAGER_FLAG AS PRIMARY_MANAGER_FLAG 
 FROM {{ ref('DW_MANAGER_DN_DH') }} DNDH
 WHERE  CURRENT_DATE() BETWEEN PARSE_DATE('%Y-%m-%d',DNDH.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',DNDH.EFFECTIVE_END_DATE)

