 SELECT  DISTINCT  DWPERDISABI.PERSON_ID AS PERSON_ID , 
  DWPERDISABI.LEGISLATION_CODE AS LEGISLATION_CODE , 
  DWPERDISABI.DW_DATE_FROM AS EFFECTIVE_START_DATE 
 FROM {{ ref('DW_PERSON_DISABILITY_D') }} DWPERDISABI
 WHERE  DWPERDISABI.LEGISLATION_CODE IS NOT NULL
