 SELECT 	DISABILITY.PERSON_ID AS PERSON_ID	, 
 	DISABILITY.LEGISLATION_CODE AS LEGISLATION_CODE	, 
 	DISABILITY.DATE_FROM AS DATE_FROM	
 --	DISABILITY.DISABILITY_FLAG AS DISABILITY_FLAG	
 FROM {{ ref('DW_PERSON_LEGISLATION_ALL_D_STAGE') }} DISABILITY

