 SELECT GRADEPVO.GRADEID AS GRADE_ID, 
 GRADEPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 GRADEPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 CAST(GRADEPVO.GRADEID AS STRING) ||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', GRADEPVO.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', GRADEPVO.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID, 
 GRADEPVO.GRADEPEOACTIVESTATUS AS ACTIVE_STATUS, 
 GRADEPVO.GRADEPEOGRADECODE AS GRADE_CODE, 
 GRADEPVO.GRADEPEOGRADETYPE AS GRADE_TYPE
 FROM {{ ref('stg_h_gradeam_gradepvo') }} GRADEPVO

