 SELECT 	TMPLPRD.TEMPLATEPERIODBPEOTMPLPERIODID AS TEMPLATE_PERIOD_ID		, 
 	TMPLPRD.TEMPLATEPERIODBPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID		, 
 	TO_CHAR(TMPLPRD.TEMPLATEPERIODBPEOTMPLPERIODID)||'~'||TO_CHAR(TMPLPRD.TEMPLATEPERIODBPEOBUSINESSGROUPID) AS SOURCE_RECORD_ID		, 
 	TMPLPRD.TEMPLATEPERIODBPEOTEMPLATEDEFNID AS TEMPLATE_DEFINITION_ID	, 
 	TMPLPRD.TEMPLATEPERIODBPEONOMINALFROMDATE AS VALID_FROM_DATE			, 
 	TMPLPRD.TEMPLATEPERIODBPEONOMINALTODATE AS VALID_TO_DATE			
 FROM {{ ref('stg_h_hcmperformancedocsam_templateperiodevaluationpvo') }} TMPLPRD

