 SELECT POSCUR.POSITION_ID AS POSITION_ID, 
 POSCUR.SOURCE_RECORD_ID AS SOURCE_RECORD_ID, 
 POSCUR.POSITION_CODE AS POSITION_CODE, 
 POSCUR.ACTIVE_STATUS AS ACTIVE_STATUS, 
 POSCUR.POSITION_TYPE AS POSITION_TYPE, 
 POSCUR.MAX_PERSONS AS MAX_PERSONS, 
 POSCUR.SECURITY_CLEARANCE AS SECURITY_CLEARANCE, 
 POSCUR.OVERLAP_ALLOWED AS OVERLAP_ALLOWED, 
 POSCUR.SEASONAL_FLAG AS SEASONAL_FLAG, 
 POSCUR.SEASONAL_START_DATE AS SEASONAL_START_DATE, 
 POSCUR.SEASONAL_END_DATE AS SEASONAL_END_DATE
 FROM {{ ref('DW_POSITION_D') }} POSCUR
 WHERE  CURRENT_DATE() BETWEEN PARSE_DATE('%Y-%m-%d',POSCUR.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',POSCUR.EFFECTIVE_END_DATE)

