 SELECT EVALPART.EVALPARTICIPANTID AS EVAL_PARTICIPANT_ID, 
 EVALPART.EVALPARTICIPANTID AS SOURCE_RECORD_ID, 
 EVALPART.EVALPARTICIPANTPEOEVALUATIONID AS EVALUATION_ID, 
 EVALPART.EVALPARTICIPANTPEOPERSONID AS PERSON_ID, 
 COALESCE(EVALPART.EVALPARTICIPANTPEOROLETYPECODE,'~NOVALUE~') AS ROLE_TYPE_CODE, 
 COALESCE(EVALPART.EVALPARTICIPANTPEOPARTICIPATIONSTATUS,'~NOVALUE~') AS PARTICIPATION_STATUS_CODE
 FROM {{ ref('stg_h_hcmperformancedocsam_evaluationparticipantrolepvo') }} EvalPart

