 SELECT 	PERSONHISTTEMP.PERSON_ID AS PERSON_ID	, 
 	PERSONHISTTEMP.LEGISLATION_CODE AS LEGISLATION_CODE	, 
 	PERSONHISTTEMP.DATE_FROM AS DATE_FROM	, 
 	CAST(PERSONHISTTEMP.PERSON_ID AS STRING)||'~'||PERSONHISTTEMP.LEGISLATION_CODE||'~'||FORMAT_DATE('%Y%m%d', PERSONHISTTEMP.DATE_FROM) AS SOURCE_RECORD_ID	, 
 	PERSONHISTTEMP.DATE_TO AS DATE_TO	, 
 	PERSON.PERSON_NUMBER AS PERSON_NUMBER	, 
 	PERSON.START_DATE AS START_DATE	, 
  	PERSON.CORRESPONDENCE_LANGUAGE AS CORRESPONDENCE_LANGUAGE	 , 
  	PERSON.DATE_OF_BIRTH AS DATE_OF_BIRTH	 , 
  	PERSON.DATE_OF_DEATH AS DATE_OF_DEATH	 , 
  	PERSON.COUNTRY_OF_BIRTH AS COUNTRY_OF_BIRTH	 , 
  	PERSON.REGION_OF_BIRTH AS REGION_OF_BIRTH	 , 
  	PERSON.TOWN_OF_BIRTH AS TOWN_OF_BIRTH	 , 
  	PERSON.BLOOD_TYPE AS BLOOD_TYPE	 , 
 	COALESCE(PERSONLEGISLATION.SEX,'~NOVALUE~') AS SEX	, 
 	COALESCE(PERSONLEGISLATION.MARITAL_STATUS,'~NOVALUE~') AS MARITAL_STATUS	, 
 	PERSONLEGISLATION.MARITAL_STATUS_DATE AS MARITAL_STATUS_DATE	, 
 	COALESCE(PERSONLEGISLATION.HIGHEST_EDUCATION_LEVEL,'~NOVALUE~') AS HIGHEST_EDUCATION_LEVEL	, 
 	COALESCE(PERSONETHNICITY.ETHNICITY,'~NOVALUE~') AS ETHNICITY	, 
 	COALESCE(PERSONHRELIGION.RELIGION,'~NOVALUE~') AS RELIGION	
 FROM  {{ ref('DW_PERSON_LEGISLATION_ALL_D_STAGE') }} PERSONHISTTEMP 
       INNER JOIN {{ ref('DW_PERSON_D') }} PERSON  ON PERSONHISTTEMP.PERSON_ID = PERSON.PERSON_ID 
	   LEFT OUTER JOIN  {{ ref('DW_PERSON_LEGISLATIVE_D') }} PERSONLEGISLATION  ON PERSONHISTTEMP.PERSON_ID = PERSONLEGISLATION.PERSON_ID AND PERSONHISTTEMP.LEGISLATION_CODE=PERSONLEGISLATION.LEGISLATION_CODE 
	   AND  PERSONHISTTEMP.DATE_FROM BETWEEN  PARSE_DATE('%Y-%m-%d', PERSONLEGISLATION.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d', PERSONLEGISLATION.EFFECTIVE_END_DATE)
	   LEFT OUTER JOIN  {{ ref('DW_PERSON_LEGISLATION_ALL_D_DIV_STAGE') }} PERSONDISABILITY  ON PERSONHISTTEMP.PERSON_ID = PERSONDISABILITY.PERSON_ID AND PERSONHISTTEMP.LEGISLATION_CODE=PERSONDISABILITY.LEGISLATION_CODE AND PERSONHISTTEMP.DATE_FROM = PERSONDISABILITY.DATE_FROM 
	   LEFT OUTER JOIN  {{ ref('DW_PERSON_ETHNICITY_D') }} PERSONETHNICITY  ON PERSONHISTTEMP.PERSON_ID = PERSONETHNICITY.PERSON_ID AND PERSONHISTTEMP.LEGISLATION_CODE=PERSONETHNICITY.LEGISLATION_CODE 
	   LEFT OUTER JOIN  {{ ref('DW_PERSON_RELIGION_D') }} PERSONHRELIGION  ON PERSONHISTTEMP.PERSON_ID = PERSONHRELIGION.PERSON_ID AND PERSONHISTTEMP.LEGISLATION_CODE=PERSONHRELIGION.LEGISLATION_CODE

