 SELECT  	PER_RELIGIONS.RELIGIONID AS RELIGION_ID	 , 
  	PER_RELIGIONS.RELIGIONID AS SOURCE_RECORD_ID	 , 
  	PER_RELIGIONS.RELIGIONPEOPERSONID AS PERSON_ID	 , 
  	PER_RELIGIONS.RELIGIONPEOLEGISLATIONCODE AS LEGISLATION_CODE	 , 
  	COALESCE(PER_RELIGIONS.RELIGIONPEORELIGION,'~NOVALUE~') AS RELIGION	 
 FROM {{ ref('stg_h_personam_religionpvoviewall') }} PER_RELIGIONS
 WHERE  PER_RELIGIONS.RELIGIONPEOPRIMARYFLAG='Y'
