 SELECT  	PERSON.PERSONID AS PERSON_ID	 , 
  	PERSON.PERSONID AS SOURCE_RECORD_ID	 , 
 	COALESCE(PERSONDETAILSPVO.PERSONDETAILSPEOPERSONNUMBER,'~NOVALUE~') AS PERSON_NUMBER	, 
 	PERSON.PERSONPEOSTARTDATE AS START_DATE	, 
  	PERSON.PERSONPEOCORRESPONDENCELANGUAGE AS CORRESPONDENCE_LANGUAGE	 , 
  	PERSON.PERSONPEODATEOFBIRTH AS DATE_OF_BIRTH	 , 
  	PERSON.PERSONPEODATEOFDEATH AS DATE_OF_DEATH	 , 
  	PERSON.PERSONPEOCOUNTRYOFBIRTH AS COUNTRY_OF_BIRTH	 , 
  	PERSON.PERSONPEOREGIONOFBIRTH AS REGION_OF_BIRTH	 , 
  	PERSON.PERSONPEOTOWNOFBIRTH AS TOWN_OF_BIRTH	 , 
  	PERSON.PERSONPEOBLOODTYPE AS BLOOD_TYPE	 
 FROM  {{ ref('stg_h_personam_personpvo') }} PERSON LEFT OUTER JOIN {{ ref('stg_h_personam_persondetailspvo') }} PERSONDETAILSPVO  ON PERSON.PERSONID=PERSONDETAILSPVO.PERSONID
 WHERE 	COALESCE(PARSE_DATE('%Y-%m-%d', PERSONDETAILSPVO.EFFECTIVEENDDATE) ,CURRENT_DATE()+1)>CURRENT_DATE()
