 SELECT GRADEPVO.GRADEID AS GRADE_ID, 
 GRADEPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 GRADEPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 TO_CHAR(GRADEPVO.GRADEID) ||'~'|| TO_CHAR(GRADEPVO.EFFECTIVESTARTDATE,'YYYYMMDD') ||'~'||TO_CHAR(GRADEPVO.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID, 
 GRADEPVO.GRADEPEOACTIVESTATUS AS ACTIVE_STATUS, 
 GRADEPVO.GRADEPEOGRADECODE AS GRADE_CODE, 
 GRADEPVO.GRADEPEOGRADETYPE AS GRADE_TYPE
 FROM {{ ref('stg_h_gradeam_gradepvo') }} GradePVO

