 SELECT CHECKIN.CHECKINTEMPLATEPEOCHECKINTEMPLATEID AS CHECK_IN_TEMPLATE_ID, 
 CHECKIN.CHECKINTEMPLATEPEOBUSINESSGROUPID AS BUSINESS_GROUP_ID, 
 CHECKIN.CHECKINTEMPLATEPEOCHECKINTEMPLATEID||'~'||CHECKIN.CHECKINTEMPLATEPEOBUSINESSGROUPID AS SOURCE_RECORD_ID, 
 COALESCE(CHECKIN.CHECKINTEMPLATEPEOSTATUSCODE,'~NOVALUE~') AS STATUS_CODE, 
 COALESCE(CHECKIN.CHECKINTEMPLATEPEOPERFORMANCEGOALSFLAG,'~NOVALUE~') AS PERFORMANCE_GOALS_FLAG, 
 COALESCE(CHECKIN.CHECKINTEMPLATEPEODEVELOPMENTGOALSFLAG,'~NOVALUE~') AS DEVELOPMENT_GOALS_FLAG, 
 COALESCE(CHECKIN.CHECKINTEMPLATEPEOGENERALDISCUSSIONTOPICFLAG,'~NOVALUE~') AS GENERAL_DISCUSSION_TOPIC_FLAG, 
 CHECKIN.CHECKINTEMPLATEPEODATEFROM AS VALID_FROM_DATE, 
 CHECKIN.CHECKINTEMPLATEPEODATETO AS VALID_TO_DATE
 FROM {{ ref('stg_h_hcmperformancesetupam_checkintemplatepvo') }} CheckIn

