  SELECT POSITIONPVO.POSITIONID AS POSITION_ID, 
 POSITIONPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 POSITIONPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 CAST(POSITIONPVO.POSITIONID AS STRING) ||'~'|| FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', POSITIONPVO.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', POSITIONPVO.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID, 
 POSITIONPVO.POSITIONPEOPOSITIONCODE AS POSITION_CODE, 
 POSITIONPVO.POSITIONPEOACTIVESTATUS AS ACTIVE_STATUS, 
 COALESCE(POSITIONPVO.POSITIONPEOPOSITIONTYPE,'~NOVALUE~') AS POSITION_TYPE, 
 COALESCE(POSITIONPVO.POSITIONPEOMAXPERSONS,-99999) AS MAX_PERSONS, 
 COALESCE(CAST(POSITIONPVO.POSITIONPEOSECURITYCLEARANCE AS STRING) ,'~NOVALUE~') AS SECURITY_CLEARANCE, 
 COALESCE(CAST(POSITIONPVO.POSITIONPEOOVERLAPALLOWED AS STRING) ,'~NOVALUE~') AS OVERLAP_ALLOWED, 
 COALESCE(POSITIONPVO.POSITIONPEOSEASONALFLAG ,'~NOVALUE~') AS SEASONAL_FLAG, 
 COALESCE(PARSE_DATE('%Y-%m-%d',POSITIONPVO.POSITIONPEOSEASONALSTARTDATE ), DATE('1901-01-01')) AS SEASONAL_START_DATE, 
 COALESCE(PARSE_DATE('%Y-%m-%d',POSITIONPVO.POSITIONPEOSEASONALENDDATE ),DATE('1901-01-01')) AS SEASONAL_END_DATE
 FROM {{ ref('stg_h_positionam_positionpvo') }} POSITIONPVO

