 SELECT  	PERSONLEGISLATIVE.PERSONLEGISLATIVEID AS PERSON_LEGISLATIVE_ID	 , 
 	PERSONLEGISLATIVE.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE	, 
 	PERSONLEGISLATIVE.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE	, 
  	CAST(PERSONLEGISLATIVE.PERSONLEGISLATIVEID AS STRING)||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', PERSONLEGISLATIVE.EFFECTIVESTARTDATE))||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', PERSONLEGISLATIVE.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID	 , 
 	PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOPERSONID AS PERSON_ID	, 
 		PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOLEGISLATIONCODE AS LEGISLATION_CODE	, 
 		COALESCE(PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOSEX,'~NOVALUE~') AS SEX	, 
 		COALESCE(PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOMARITALSTATUS,'~NOVALUE~') AS MARITAL_STATUS	, 
 		PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOMARITALSTATUSDATE AS MARITAL_STATUS_DATE	, 
 		COALESCE(PERSONLEGISLATIVE.PERSONLEGISLATIVEINFODPEOHIGHESTEDUCATIONLEVEL,'~NOVALUE~') AS HIGHEST_EDUCATION_LEVEL	, 
 CASE WHEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') > PARSE_DATE('%Y-%m-%d', PERSONLEGISLATIVE.EFFECTIVESTARTDATE ) THEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') ELSE PARSE_DATE('%Y-%m-%d', PERSONLEGISLATIVE.EFFECTIVESTARTDATE) END AS DW_DATE_FROM, 
 PERSONLEGISLATIVE.EFFECTIVEENDDATE AS DW_DATE_TO, 
   CASE WHEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') > PARSE_DATE('%Y-%m-%d', PERSONLEGISLATIVE.EFFECTIVESTARTDATE)  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM {{ ref('stg_h_personam_personlegislativeinfopvoviewall') }} PERSONLEGISLATIVE

