 SELECT  	PER_CITIZENSHIPS.CITIZENSHIPID AS CITIZENSHIP_ID	 , 
  	PER_CITIZENSHIPS.CITIZENSHIPID AS SOURCE_RECORD_ID	 , 
 	PER_CITIZENSHIPS.CITIZENSHIPPEODATEFROM AS DATE_FROM	, 
 	PER_CITIZENSHIPS.CITIZENSHIPPEODATETO AS DATE_TO	, 
  	PER_CITIZENSHIPS.CITIZENSHIPPEOPERSONID AS PERSON_ID	 , 
  	PER_CITIZENSHIPS.CITIZENSHIPPEOLEGISLATIONCODE AS LEGISLATION_CODE	 , 
  	COALESCE(PER_CITIZENSHIPS.CITIZENSHIPPEOCITIZENSHIPSTATUS,'~NOVALUE~') AS CITIZENSHIP_STATUS	 
 FROM {{ ref('stg_h_personam_citizenshippvoviewall') }} PER_CITIZENSHIPS

