 SELECT  DW_PERSON_HISTORY_STAGE_TEMP.PERSON_ID AS PERSON_ID , 
  DW_PERSON_HISTORY_STAGE_TEMP.LEGISLATION_CODE AS LEGISLATION_CODE , 
  DW_PERSON_HISTORY_STAGE_TEMP.EFFECTIVE_START_DATE AS DATE_FROM , 
 	TO_DATE(SUBSTR('4712-12-31 00:00:00.0',1,19),'YYYY-MM-DD HH24:MI:SS') AS DATE_TO	
 FROM {{ ref('DW_PERSON_LEGISLATION_ALL_D_STAGE_TEMP') }} DW_PERSON_HISTORY_STAGE_TEMP

