 SELECT POSITIONPVO.POSITIONID AS POSITION_ID, 
 POSITIONPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE, 
 POSITIONPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE, 
 TO_CHAR(POSITIONPVO.POSITIONID) ||'~'|| TO_CHAR(POSITIONPVO.EFFECTIVESTARTDATE,'YYYYMMDD') ||'~'||TO_CHAR(POSITIONPVO.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID, 
 POSITIONPVO.POSITIONPEOPOSITIONCODE AS POSITION_CODE, 
 POSITIONPVO.POSITIONPEOACTIVESTATUS AS ACTIVE_STATUS, 
 COALESCE(POSITIONPVO.POSITIONPEOPOSITIONTYPE,'~NOVALUE~') AS POSITION_TYPE, 
 COALESCE(POSITIONPVO.POSITIONPEOMAXPERSONS,-99999) AS MAX_PERSONS, 
 COALESCE(POSITIONPVO.POSITIONPEOSECURITYCLEARANCE ,'~NOVALUE~') AS SECURITY_CLEARANCE, 
 COALESCE(POSITIONPVO.POSITIONPEOOVERLAPALLOWED ,'~NOVALUE~') AS OVERLAP_ALLOWED, 
 COALESCE(POSITIONPVO.POSITIONPEOSEASONALFLAG ,'~NOVALUE~') AS SEASONAL_FLAG, 
 COALESCE(POSITIONPVO.POSITIONPEOSEASONALSTARTDATE ,TO_DATE(SUBSTR('1901-01-01 00:00:00.0',1,19),'YYYY-MM-DD HH24:MI:SS')) AS SEASONAL_START_DATE, 
 COALESCE(POSITIONPVO.POSITIONPEOSEASONALENDDATE ,TO_DATE(SUBSTR('1901-01-01 00:00:00.0',1,19),'YYYY-MM-DD HH24:MI:SS')) AS SEASONAL_END_DATE
 FROM {{ ref('stg_h_positionam_positionpvo') }} PositionPVO

