 SELECT  	PER_ETHNICITIES.ETHNICITYID AS ETHNICITY_ID	 , 
  	PER_ETHNICITIES.ETHNICITYID AS SOURCE_RECORD_ID	 , 
  	PER_ETHNICITIES.ETHNICITYPEOPERSONID AS PERSON_ID	 , 
  	PER_ETHNICITIES.ETHNICITYPEOLEGISLATIONCODE AS LEGISLATION_CODE	 , 
  	COALESCE(PER_ETHNICITIES.ETHNICITYPEOETHNICITY,'~NOVALUE~') AS ETHNICITY	 
 FROM {{ ref('stg_h_personam_personethinicitypvoviewall') }} PER_ETHNICITIES
 WHERE  PER_ETHNICITIES.ETHNICITYPEOPRIMARYFLAG='Y'
