 SELECT 	TMPLDEF.TEMPLATEDEFNID AS TEMPLATE_DEFINITION_ID	, 
 	TMPLDEF.BUSINESSGROUPID AS BUSINESS_GROUP_ID     	, 
 	TO_CHAR(TMPLDEF.TEMPLATEDEFNID)||'~'||TO_CHAR(TMPLDEF.BUSINESSGROUPID) AS SOURCE_RECORD_ID      	, 
 	TMPLDEF.TEMPLATETYPECODE AS TEMPLATE_TYPE_CODE    	, 
 	TMPLDEF.TEMPLATEDEFNBPEODATEFROM AS VALID_FROM_DATE       	, 
 	TMPLDEF.TEMPLATEDEFNBPEODATETO AS VALID_TO_DATE         	, 
 	TMPLDEF.TEMPLATEDEFNBPEOSTATUSCODE AS TEMPLATE_STATUS_CODE  	, 
 	TMPLDEF.TEMPLATEDEFNBPEODOCTYPEID AS DOC_TYPE_ID           	, 
 	TMPLDEF.TEMPLATEDEFNBPEOPROCESSFLOWID AS PROCESS_FLOW_ID       	
 FROM {{ ref('stg_h_hcmperformancesetupam_templatedefnpvo') }} TMPLDEF

