 SELECT  	PERSONNAME.PERSON_NAME_ID AS PERSON_NAME_ID	 , 
  	PERSONNAME.PERSON_NAME_ID AS SOURCE_RECORD_ID	 , 
 	PERSONNAME.PERSON_ID AS PERSON_ID	, 
 		PERSONNAME.LEGISLATION_CODE AS LEGISLATION_CODE	, 
 		PERSONNAME.NAME_TYPE AS NAME_TYPE	, 
 		PERSONNAME.DISPLAY_NAME AS DISPLAY_NAME	, 
 		PERSONNAME.FIRST_NAME AS FIRST_NAME	, 
 		PERSONNAME.LAST_NAME AS LAST_NAME	, 
 		PERSONNAME.MIDDLE_NAMES AS MIDDLE_NAMES	, 
 		PERSONNAME.TITLE AS TITLE	, 
 		PERSONNAME.PRE_NAME_ADJUNCT AS PRE_NAME_ADJUNCT	, 
 		PERSONNAME.SUFFIX AS SUFFIX	, 
 		PERSONNAME.KNOWN_AS AS KNOWN_AS	, 
 		PERSONNAME.PREVIOUS_LAST_NAME AS PREVIOUS_LAST_NAME	, 
 	PERSONNAME.FULL_NAME AS FULL_NAME	, 
 	PERSONNAME.LIST_NAME AS LIST_NAME	, 
 	PERSONNAME.ORDER_NAME AS ORDER_NAME	
 FROM {{ ref('DW_PERSON_NAME_D') }} PERSONNAME
 WHERE  CURRENT_DATE() BETWEEN PARSE_DATE('%Y-%m-%d',PERSONNAME.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',PERSONNAME.EFFECTIVE_END_DATE)

