 SELECT RLEVPVO.RATINGLEVELBPEORATINGLEVELID AS RATING_LEVEL_ID, 
 RLEVPVO.RATINGLEVELBPEORATINGMODELID AS RATING_MODEL_ID, 
 COALESCE(CAST(RCATPVO.RATINGCATEGORIESBPEOCATEGORYID AS INT64),-99999) AS CATEGORY_ID, 
 CAST(RLEVPVO.RATINGLEVELBPEORATINGLEVELID AS STRING) ||'~'|| CAST(RLEVPVO.RATINGLEVELBPEORATINGMODELID  AS STRING) ||'~'||COALESCE(RCATPVO.RATINGCATEGORIESBPEORATINGMODELID,-99999) AS SOURCE_RECORD_ID, 
 RLEVPVO.RATINGLEVELBPEORATINGLEVELCODE AS RATING_LEVEL_CODE, 
 MODPVO.RATINGMODELBPEORATINGMODELCODE AS RATING_MODEL_CODE, 
 RLEVPVO.RATINGLEVELBPEONUMERICRATING AS NUMERIC_RATING
 FROM  {{ ref('stg_h_hcmprofilecontentlibraryam_ratinglevelfirstpvo') }} RLEVPVO 
 INNER JOIN {{ ref('stg_h_hcmprofilecontentlibraryam_ratingmodelfirstpvo') }} MODPVO  ON (RLEVPVO.RATINGLEVELBPEORATINGMODELID=MODPVO.RATINGMODELBPEORATINGMODELID AND RLEVPVO.RATINGLEVELBPEOBUSINESSGROUPID=MODPVO.RATINGMODELBPEOBUSINESSGROUPID) 
 LEFT OUTER JOIN  {{ ref('stg_h_hcmprofilecontentlibraryam_ratingcategoriesfirstpvo') }} RCATPVO  ON 	(RLEVPVO.RATINGLEVELBPEORATINGMODELID=RCATPVO.RATINGCATEGORIESBPEORATINGMODELID AND RLEVPVO.RATINGLEVELBPEOBUSINESSGROUPID=RCATPVO.RATINGCATEGORIESBPEOBUSINESSGROUPID) 

