 SELECT REVIEW.REVIEWPERIODID AS REVIEW_PERIOD_ID, 
 REVIEW.REVIEWPERIODID AS SOURCE_RECORD_ID, 
 REVIEW.BUSINESSGROUPID AS BUSINESS_GROUP_ID, 
 REVIEW.STARTDATE AS START_DATE, 
 REVIEW.ENDDATE AS END_DATE, 
 REVIEW.STATUSCODE AS STATUS_CODE
 FROM {{ ref('stg_h_hcmprofilecoream_reviewperiodpvo') }} Review

