 SELECT    WORKRELATIONSHIPPVO.PERIODOFSERVICEID AS PERIOD_OF_SERVICE_ID   , 
    CAST(WORKRELATIONSHIPPVO.PERIODOFSERVICEID AS STRING) AS SOURCE_RECORD_ID       , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOPERSONID AS PERSON_ID              , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOLEGISLATIONCODE AS LEGISLATION_CODE       , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEODATESTART AS DATE_START             , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOACTUALTERMINATIONDATE AS ACTUAL_TERMINATION_DATE     , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEONOTIFIEDTERMINATIONDATE AS NOTIFIED_TERMINATION_DATE   , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOPROJECTEDTERMINATIONDATE AS PROJECTED_TERMINATION_DATE  , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOLASTWORKINGDATE AS LAST_WORKING_DATE           , 
    WORKRELATIONSHIPPVO.WORKRELATIONSHIPPEOPRIMARYFLAG AS PRIMARY_FLAG                
 FROM {{ ref('stg_h_assignmentam_workrelationshippvo') }} WorkRelationshipPVO

