SELECT SALARYBASISPVO.SALARYBASISID AS SALARY_BASIS_ID, 
 CAST(SALARYBASISPVO.SALARYBASISID AS STRING) AS SOURCE_RECORD_ID, 
 SALARYBASISPVO.SALARYBASISPEOANNUALIZEDHOURS AS ANNUALIZED_HOURS, 
 COALESCE(SALARYBASISPVO.SALARYBASISPEOELEMENTTYPEID,-99999) AS ELEMENT_TYPE_ID, 
 COALESCE(SALARYBASISPVO.SALARYBASISPEOGRADERATEID,-99999) AS GRADE_RATE_ID, 
 COALESCE(SALARYBASISPVO.SALARYBASISPEOSALARYBASISCODE,'~NOVALUE~') AS SALARY_BASIS_CODE, 
 SALARYBASISPVO.SALARYBASISPEOSALARYANNUALIZATIONFACTOR AS SALARY_ANNUALIZATION_FACTOR
 FROM {{ ref('stg_h_gradeam_salarybasispvo') }} SALARYBASISPVO

