 SELECT USERPVO.USERPEOUSERID AS USER_ID, 
 TO_CHAR(USERPVO.USERPEOUSERID) AS SOURCE_RECORD_ID, 
 USERPVO.USERPEOUSERGUID AS USER_GUID, 
 COALESCE(USERPVO.USERPEOUSERNAME,'~NOVALUE~') AS USERNAME, 
 COALESCE(USERPVO.USERPEOPERSONID,-99999) AS PERSON_ID
 FROM {{ ref('stg_h_useram_userpvo') }} UserPVO

