 SELECT  SUP.ASSIGNMENT_ID AS ASSIGNMENT_ID                  , 
  SUP.EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE           , 
  CAST(SUP.ASSIGNMENT_ID AS STRING)||'~'||FORMAT_DATE('%Y%m%d',SUP.EFFECTIVE_START_DATE) AS SOURCE_RECORD_ID               , 
  SUP.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE             , 
  COALESCE(SPAN.WORKER_TYPE,'~NOVALUE~') AS WORKER_TYPE                    , 
  COALESCE(SPAN.PERSON_ID,-99999) AS PERSON_ID                      
 FROM  {{ ref('DW_WRKFRC_SUP_FL_DT_STAGE') }} SUP INNER JOIN {{ ref('DW_WRKFRC_ASG_SPAN_DT_STAGE') }} SPAN  ON (SUP.ASSIGNMENT_ID = SPAN.ASSIGNMENT_ID)
 WHERE  SUP.COMPUTE_NEXT_DT_FLAG ='Y' AND SPAN.WORKER_TYPE<>'P' AND SUP.EFFECTIVE_END_DATE>=SUP.EFFECTIVE_START_DATE
