 SELECT  WRKFCASG.ASSIGNMENT_ID AS ASSIGNMENT_ID , 
  WRKFCASG.EFFECTIVE_START_DATE AS PROMOTION_DATE , 
 	DATE('4712-12-31') AS NEXT_PROMOTION_DATE	, 
 	MAX(CASE WHEN ACTION.ACTION_TYPE_CODE <>'EMPL_PROMOTION' THEN 1 ELSE 0 END) AS HIRE_EVENT_IND	, 
  MAX(CASE WHEN ACTION.ACTION_TYPE_CODE ='EMPL_PROMOTION' THEN 1 ELSE 0 END) AS PROMOTION_EVENT_IND 
 FROM  {{ ref('DW_WRKFRC_ASG_F') }} WRKFCASG INNER JOIN {{ ref('DW_ACTION_D') }} ACTION  ON WRKFCASG.ACTION_ID = ACTION.ACTION_ID
 WHERE 	ACTION.ACTION_TYPE_CODE IN ('EMPL_WR_EMP', 'EMPL_ADD_EMP', 'EMPL_REHIRE','EMPL_ADD_CWK', 'EMPL_WR_CWK','EMPL_ADD_NWK','EMPL_ADD_PWK','EMPL_PROMOTION') GROUP BY  WRKFCASG.ASSIGNMENT_ID, WRKFCASG.EFFECTIVE_START_DATE,	DATE('4712-12-31')
