 SELECT  DISTINCT  FP.FISCAL_PERIOD_SET_NAME AS FISCAL_PERIOD_SET_NAME , 
  FP.FISCAL_PERIOD_TYPE AS FISCAL_PERIOD_TYPE , 
  FP.FISCAL_YEAR_NUMBER AS FISCAL_YEAR_NUMBER , 
  FP.FISCAL_PERIOD_SET_NAME||'~'||FP.FISCAL_PERIOD_TYPE||'~'||FP.FISCAL_YEAR_NUMBER AS SOURCE_RECORD_ID , 
  FP.FISCAL_YEAR_START_DATE AS FISCAL_YEAR_START_DATE , 
  FP.FISCAL_YEAR_START_DATE_ID AS FISCAL_YEAR_START_DATE_ID , 
  FP.FISCAL_YEAR_END_DATE AS FISCAL_YEAR_END_DATE , 
  FP.FISCAL_YEAR_END_DATE_ID AS FISCAL_YEAR_END_DATE_ID , 
  FP.FISCAL_YEAR_TOTAL_WEEKS AS FISCAL_YEAR_TOTAL_WEEKS , 
  FP.FISCAL_YEAR_TOTAL_DAYS AS FISCAL_YEAR_TOTAL_DAYS , 
  FP.CURRENT_FISCAL_YEAR_CODE AS CURRENT_FISCAL_YEAR_CODE 
 FROM {{ ref('DW_FISCAL_PERIOD_D') }} FP
 WHERE 	FP.FISCAL_PERIOD_SET_NAME <> '~NOVALUE~' AND FP.ADJUSTMENT_PERIOD_FLAG <> 'Y'
