 SELECT  DISTINCT BUSINESSUNITPVO.BUSINESSUNITID AS ORGANIZATION_ID, 
 -1 AS LEDGER_ID, 
 LEDGERPVO2.GLCALENDARSPERIODSETNAME AS FISCAL_PERIOD_SET_NAME, 
 LEDGERPVO2.GLCALENDARSPERIODTYPE AS FISCAL_PERIOD_TYPE, 
 BUSINESSUNITPVO.BUSINESSUNITID||'~' || LEDGERPVO2.GLCALENDARSPERIODSETNAME|| '~' ||LEDGERPVO2.GLCALENDARSPERIODTYPE || '~' AS SOURCE_RECORD_ID, 
 CAST (NULL AS STRING) AS LEDGER_NAME
 FROM  {{ ref('stg_f_finfunbusinessunitsam_businessunitpvo') }} BUSINESSUNITPVO INNER JOIN {{ ref('stg_f_finglledgerdefnam_ledgerpvo') }} LEDGERPVO2  ON BUSINESSUNITPVO.LEDGERLEDGERID=LEDGERPVO2.LEDGERID

