 SELECT DAY.CAL_WEEK_ID AS CAL_WEEK_ID, 
 DAY.CAL_WEEK_ID AS SOURCE_RECORD_ID, 
 DAY.CAL_YEAR_ID AS CAL_YEAR_ID, 
 DAY.CAL_WEEK_CODE AS CAL_WEEK_CODE, 
 DAY.CAL_WEEK_START_DATE AS CAL_WEEK_START_DATE, 
 DAY.CAL_WEEK_END_DATE AS CAL_WEEK_END_DATE, 
 DAY.CAL_YEAR_START_DATE AS CAL_YEAR_START_DATE, 
 DAY.CAL_YEAR_END_DATE AS CAL_YEAR_END_DATE, 
 DAY.CAL_WEEK_NUMBER AS CAL_WEEK_NUMBER, 
 DAY.CAL_WEEK_END_DATE_ID AS CAL_WEEK_END_DATE_ID, 
 DAY.CAL_WEEK_START_DATE_ID AS CAL_WEEK_START_DATE_ID, 
 DAY.CAL_YEAR_END_DATE_ID AS CAL_YEAR_END_DATE_ID, 
 DAY.CAL_YEAR_START_DATE_ID AS CAL_YEAR_START_DATE_ID, 
 MAX(CASE WHEN DAY.CAL_WEEK_START_DATE=DAY.CAL_YEAR_START_DATE THEN 'Y' ELSE 'N' END) AS FIRST_WEEK_CAL_YEAR_FLAG, 
 MAX(CASE WHEN DAY.CAL_WEEK_END_DATE=DAY.CAL_YEAR_END_DATE THEN 'Y' ELSE 'N' END) AS LAST_WEEK_CAL_YEAR_FLAG, 
 DAY.CURRENT_CAL_WEEK_CODE AS CURRENT_CAL_WEEK_CODE, 
 DAY.CURRENT_CAL_YEAR_CODE AS CURRENT_CAL_YEAR_CODE
 FROM {{ ref('DW_DAY_D') }} day
 GROUP BY DAY.CAL_WEEK_ID,DAY.CAL_WEEK_ID,DAY.CAL_YEAR_ID,DAY.CAL_WEEK_CODE,DAY.CAL_WEEK_START_DATE,DAY.CAL_WEEK_END_DATE,DAY.CAL_YEAR_START_DATE,DAY.CAL_YEAR_END_DATE,DAY.CAL_WEEK_NUMBER,DAY.CAL_WEEK_END_DATE_ID,DAY.CAL_WEEK_START_DATE_ID,DAY.CAL_YEAR_END_DATE_ID,DAY.CAL_YEAR_START_DATE_ID,DAY.CURRENT_CAL_WEEK_CODE,DAY.CURRENT_CAL_YEAR_CODE
