 SELECT  DISTINCT DAY.CAL_YEAR_ID AS CAL_YEAR_ID, 
 DAY.CAL_YEAR_ID AS SOURCE_RECORD_ID, 
 DAY.CAL_YEAR_START_DATE AS CAL_YEAR_START_DATE, 
 DAY.CAL_YEAR_END_DATE AS CAL_YEAR_END_DATE, 
 DAY.CAL_YEAR_END_DATE_ID AS CAL_YEAR_END_DATE_ID, 
 DAY.CAL_YEAR_START_DATE_ID AS CAL_YEAR_START_DATE_ID, 
 DAY.CURRENT_CAL_YEAR_CODE AS CURRENT_CAL_YEAR_CODE, 
 DAY.YEAR_END_OR_PRV_CRNT_DATE AS YEAR_END_OR_PRV_CRNT_DATE
 FROM {{ ref('DW_DAY_D') }} day

