 SELECT SALARYPVO.SALARYID AS SALARY_ID, 
 TO_CHAR(SALARYPVO.SALARYID) AS SOURCE_RECORD_ID, 
 SALARYPVO.SALARYPEOASSIGNMENTID AS ASSIGNMENT_ID, 
 SALARYPVO.SALARYPEOSALARYBASISID AS SALARY_BASIS_ID, 
 SALARYPVO.SALARYPEODATEFROM AS EFFECTIVE_START_DATE, 
 SALARYPVO.SALARYPEODATETO AS EFFECTIVE_END_DATE, 
 SALARYPVO.SALARYPEOSALARYAPPROVED AS SALARY_APPROVED, 
 COALESCE(SALARYPVO.SALARYPEOACTIONOCCURRENCEID,-99999) AS ACTION_OCCURRENCE_ID, 
 COALESCE(SALARYPVO.SALARYPEOACTIONID,-99999) AS ACTION_ID, 
 COALESCE(SALARYPVO.SALARYPEOACTIONREASONID,-99999) AS ACTION_REASON_ID, 
 SALARYPVO.SALARYPEOSALARYAMOUNT AS SALARY_AMOUNT, 
  COALESCE(ELEMENTTYPE.ELEMENTTYPEOUTPUTCURRENCYCODE,'~NOVALUE~') AS CURRENCY_CODE, 
 GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),SALARYPVO.SALARYPEODATEFROM) AS DW_DATE_FROM, 
 SALARYPVO.SALARYPEODATETO AS DW_DATE_TO, 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') > SALARYPVO.SALARYPEODATEFROM  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM  {{ ref('stg_h_compensationam_salarypvo') }} SALARYPVO
       INNER JOIN {{ ref('stg_h_gradeam_salarybasispvo') }} SALARYBASISPVO  ON SALARYPVO.SALARYPEOSALARYBASISID=SALARYBASISPVO.SALARYBASISID 
       INNER JOIN  {{ ref('stg_h_hcmelementsetupam_originatingelement') }} ELEMENTTYPE  ON SALARYBASISPVO.SALARYBASISPEOELEMENTTYPEID=ELEMENTTYPE.ELEMENTTYPEID AND SALARYPVO.SALARYPEODATEFROM >=ELEMENTTYPE.EFFECTIVESTARTDATE AND SALARYPVO.SALARYPEODATEFROM <=ELEMENTTYPE.EFFECTIVEENDDATE 

