 SELECT POTVO.PROFILEITEMID AS PROFILE_ITEM_ID, 
 CAST(POTVO.PROFILEITEMID AS STRING) AS SOURCE_RECORD_ID, 
 COALESCE(PERSNVO.PROFILEBPEOPERSONID,-99999) AS PERSON_ID, 
 COALESCE(POTVO.RATINGLEVELID1,-99999) AS RATING_LEVEL_ID, 
 POTVO.DATEFROM AS DATE_FROM, 
COALESCE(PARSE_DATE('%Y-%m-%d',POTVO.DATETO),DATE('4712-12-31')) AS DATE_TO, 
 CASE WHEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') > PARSE_DATE('%Y-%m-%d', POTVO.DATEFROM ) THEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') ELSE PARSE_DATE('%Y-%m-%d', POTVO.DATEFROM) END AS DW_DATE_FROM,
 COALESCE(PARSE_DATE('%Y-%m-%d',POTVO.DATETO),DATE('4712-12-31')) AS DW_DATE_TO, 
 CASE WHEN PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') > PARSE_DATE('%Y-%m-%d', POTVO.DATEFROM)  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM  {{ ref('stg_h_hcmprofilecoream_potentialpvoprofileitemref') }} PotVO INNER JOIN {{ ref('stg_h_hcmprofilecoream_personprofileitempvo') }} PersnVO  ON POTVO.PROFILEID=PERSNVO.PROFILEBPEOPROFILEID 
 WHERE  POTVO.CONTENTTYPEID=113
