 SELECT  PERSONLEG.PERSON_ID AS PERSON_ID , 
  PERSONLEG.LEGISLATION_CODE AS LEGISLATION_CODE , 
  PERSONLEG.DATE_FROM AS EVENT_DATE , 
  CAST(PERSONLEG.PERSON_ID AS STRING)||'~'||PERSONLEG.LEGISLATION_CODE||'~'||FORMAT_DATE('%Y%m%d',PERSONLEG.DATE_FROM) AS SOURCE_RECORD_ID , 
  PERSONLEG.SEX AS SEX , 
  PERSONLEG.MARITAL_STATUS AS MARITAL_STATUS , 
  PERSONLEG.HIGHEST_EDUCATION_LEVEL AS HIGHEST_EDUCATION_LEVEL , 
--  PERSONLEG.DISABILITY_FLAG AS DISABILITY_FLAG , 
  PERSONLEG.ETHNICITY AS ETHNICITY , 
  PERSONLEG.RELIGION AS RELIGION , 
  PERSONLEG.DATE_OF_BIRTH AS DATE_OF_BIRTH , 
 	ROUND( (DATE_DIFF(PERSONLEG.DATE_FROM, PARSE_DATE('%Y-%m-%d',PERSONLEG.DATE_OF_BIRTH), DAY)/365),2) AS AGE_IN_YEARS	, 
 	0 AS SEX_CHANGE_IND	, 
 	0 AS MARITAL_STATUS_CHANGE_IND	, 
 	0 AS HIGHEST_EDUCATION_CHANGE_IND	, 
 	0 AS DISABILITY_FLAG_CHANGE_IND	
 FROM {{ ref('DW_PERSON_LEGISLATION_ALL_D') }} PERSONLEG

