 SELECT POTVO.PROFILEITEMID AS PROFILE_ITEM_ID, 
 TO_CHAR(POTVO.PROFILEITEMID) AS SOURCE_RECORD_ID, 
 COALESCE(PERSNVO.PROFILEBPEOPERSONID,-99999) AS PERSON_ID, 
 COALESCE(POTVO.RATINGLEVELID1,-99999) AS RATING_LEVEL_ID, 
 POTVO.DATEFROM AS DATE_FROM, 
 COALESCE(POTVO.DATETO,TO_DATE(SUBSTR('4712-12-31 00:00:00.0',1,19),'YYYY-MM-DD HH24:MI:SS')) AS DATE_TO, 
 GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),POTVO.DATEFROM) AS DW_DATE_FROM, 
 COALESCE(POTVO.DATETO,TO_DATE(SUBSTR('4712-12-31 00:00:00.0',1,19),'YYYY-MM-DD HH24:MI:SS')) AS DW_DATE_TO, 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') > POTVO.DATEFROM  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND
 FROM  {{ ref('stg_h_hcmprofilecoream_potentialpvoprofileitemref') }} PotVO INNER JOIN {{ ref('stg_h_hcmprofilecoream_personprofileitempvo') }} PersnVO  ON POTVO.PROFILEID=PERSNVO.PROFILEBPEOPROFILEID 
 WHERE  POTVO.CONTENTTYPEID=113
