 SELECT  PERSONEVENT.PERSON_ID AS PERSON_ID , 
  PERSONEVENT.LEGISLATION_CODE AS LEGISLATION_CODE , 
  PERSONEVENT.EVENT_DATE AS EVENT_DATE , 
 	$$$PREVIOUS_CHANGE_IND$$$(PERSONEVENT.SEX,PERSONEVENT.SEX_CHANGE_IND) AS SEX_CHANGE_IND	, 
 	$$$PREVIOUS_CHANGE_IND$$$(PERSONEVENT.MARITAL_STATUS,PERSONEVENT.MARITAL_STATUS_CHANGE_IND) AS MARITAL_STATUS_CHANGE_IND	, 
 	$$$PREVIOUS_CHANGE_IND$$$(PERSONEVENT.HIGHEST_EDUCATION_LEVEL,PERSONEVENT.HIGHEST_EDUCATION_CHANGE_IND) AS HIGHEST_EDUCATION_CHANGE_IND	, 
 	$$$PREVIOUS_CHANGE_IND$$$(PERSONEVENT.DISABILITY_FLAG,PERSONEVENT.DISABILITY_FLAG_CHANGE_IND) AS DISABILITY_FLAG_CHANGE_IND	
 FROM  'DW_PERSON_LEGISLATION_DAILY_EVENT_F' PERSONEVENT INNER JOIN 'DW_PERSON_LEGISLATION_DAILY_EVENT_F_TEMP' TEMP  ON PERSONEVENT.PERSON_ID = TEMP.PERSON_ID AND PERSONEVENT.LEGISLATION_CODE = TEMP.LEGISLATION_CODE

