 SELECT  FTF.ASSIGNMENT_ID AS ASSIGNMENT_ID                  , 
  FTF.EFFECTIVE_END_DATE+1 AS EFFECTIVE_START_DATE           , 
  CAST(FTF.ASSIGNMENT_ID AS STRING)||'~'||TO_CHAR((FTF.EFFECTIVE_END_DATE+1),'YYYYMMDD') AS SOURCE_RECORD_ID               , 
  SPASG.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE             , 
  'Y' AS COMPUTE_NEXT_DT_FLAG           
 FROM  {{ ref('DW_WRKFRC_ASG_FTE_F') }} FTF INNER JOIN {{ ref('DW_WRKFRC_ASG_SPAN_DT_STAGE') }} SPASG  ON (FTF.ASSIGNMENT_ID=SPASG.ASSIGNMENT_ID)
 WHERE  NOT EXISTS(SELECT 1 FROM  DW_WRKFRC_ASG_FTE_F FF WHERE FTF.ASSIGNMENT_ID=FF.ASSIGNMENT_ID AND FTF.EFFECTIVE_END_DATE+1 = FF.EFFECTIVE_START_DATE  ) AND SPASG.EFFECTIVE_END_DATE>FTF.EFFECTIVE_END_DATE
