 SELECT  COALESCE(ASG_HDC.ASSIGN_WORK_MEASURE_ID,FL_HDC.ASSIGNMENT_ID) AS ASSIGN_WORK_MEASURE_ID , 
  COALESCE(PARSE_DATE('%Y-%m-%d',ASG_HDC.EFFECTIVE_START_DATE),FL_HDC.EFFECTIVE_START_DATE) AS EFFECTIVE_START_DATE   , 
  FL_HDC.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE     , 
  CAST(COALESCE(ASG_HDC.ASSIGN_WORK_MEASURE_ID,-99999) AS STRING)||'~'||FORMAT_DATE('%Y%m%d',COALESCE(PARSE_DATE('%Y-%m-%d',ASG_HDC.EFFECTIVE_START_DATE),FL_HDC.EFFECTIVE_START_DATE))||'~'||FORMAT_DATE('%Y%m%d',FL_HDC.EFFECTIVE_END_DATE) AS SOURCE_RECORD_ID       , 
  FL_HDC.ASSIGNMENT_ID AS ASSIGNMENT_ID          , 
  ASG_HDC.ACTION_OCCURRENCE_ID AS ACTION_OCCURRENCE_ID   , 
  ASG_HDC.HEADCOUNT AS HEADCOUNT              , 
  0 AS HEADCOUNT_CHANGE_IND   , 
  -99999 AS PREVIOUS_HEADCOUNT     
 FROM  {{ ref('DW_WRKFRC_HDC_FL_DT_STAGE') }} FL_HDC 
 LEFT OUTER JOIN {{ ref('DW_WRKFRC_ASG_HEADCOUNT_F') }} ASG_HDC  ON 
     (FL_HDC.ASSIGNMENT_ID=ASG_HDC.ASSIGNMENT_ID AND 
     FL_HDC.EFFECTIVE_START_DATE=PARSE_DATE('%Y-%m-%d',ASG_HDC.EFFECTIVE_START_DATE))

