 SELECT  ASG_SUP.ASSIGNMENT_SUPERVISOR_ID AS ASSIGNMENT_SUPERVISOR_ID         , 
  ASG_SUP.EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE             , 
  ASG_SUP.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE                 , 
  $$$PREVIOUS_CHANGE_IND$$$(ASG_SUP.MANAGER_ASSIGNMENT_ID,ASG_SUP.MANAGER_CHANGE_IND) AS MANAGER_CHANGE_IND                 , 
  $$$PREVIOUS_VAL$$$(ASG_SUP.MANAGER_ASSIGNMENT_ID,ASG_SUP.PREVIOUS_MANAGER_ASSIGNMENT_ID) AS PREVIOUS_MANAGER_ASSIGNMENT_ID     , 
  $$$PREVIOUS_VAL$$$(ASG_SUP.MANAGER_ID,ASG_SUP.PREVIOUS_MANAGER_ID) AS PREVIOUS_MANAGER_ID             
 FROM 'DW_WRKFRC_ASG_SUP_CHANGE_STAGE' ASG_SUP

