 SELECT  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORID AS ASSIGNMENT_SUPERVISOR_ID  , 
  ASSIGNMENTSUPERVISORPVO.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE      , 
  ASSIGNMENTSUPERVISORPVO.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE        , 
  TO_CHAR(ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORID)||'~'||TO_CHAR(ASSIGNMENTSUPERVISORPVO.EFFECTIVESTARTDATE,'YYYYMMDD')||'~'||TO_CHAR(ASSIGNMENTSUPERVISORPVO.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID          , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOASSIGNMENTID AS ASSIGNMENT_ID             , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOPERSONID AS PERSON_ID                 , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOPRIMARYFLAG AS PRIMARY_FLAG              , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOMANAGERTYPE AS MANAGER_TYPE              , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOMANAGERASSIGNMENTID AS MANAGER_ASSIGNMENT_ID     , 
  ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOMANAGERID AS MANAGER_ID                , 
  COALESCE(ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID,-99999) AS ACTION_OCCURRENCE_ID      , 
  COALESCE(ACTIONSPVO.ACTIONID,-99999) AS ACTION_ID                 , 
  COALESCE(ACTIONREASONSPVO.ACTIONREASONID,-99999) AS ACTION_REASON_ID          , 
  GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),  ASSIGNMENTSUPERVISORPVO.EFFECTIVESTARTDATE) AS DW_DATE_FROM              , 
  ASSIGNMENTSUPERVISORPVO.EFFECTIVEENDDATE AS DW_DATE_TO                , 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS')  > ASSIGNMENTSUPERVISORPVO.EFFECTIVESTARTDATE THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND     
 FROM  {{ ref('stg_h_assignmentam_assignmentsupervisorpvo') }} ASSIGNMENTSUPERVISORPVO 
      LEFT OUTER JOIN {{ ref('stg_h_actionam_actionoccurrencespvo') }} ACTIONOCCURRENCESPVO  ON ASSIGNMENTSUPERVISORPVO.ASSIGNMENTSUPERVISORPEOACTIONOCCURRENCEID = ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionspvo') }} ACTIONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONID = ACTIONSPVO.ACTIONID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionreasonspvo') }} ACTIONREASONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONREASONID = ACTIONREASONSPVO.ACTIONREASONID

