 SELECT  COALESCE(ASG_SUP.ASSIGNMENT_SUPERVISOR_ID,FL_SUP.ASSIGNMENT_ID) AS ASSIGNMENT_SUPERVISOR_ID       , 
  COALESCE(PARSE_DATE('%Y-%m-%d',ASG_SUP.EFFECTIVE_START_DATE),FL_SUP.EFFECTIVE_START_DATE) AS EFFECTIVE_START_DATE           , 
  FL_SUP.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE             , 
  CAST(COALESCE(ASG_SUP.ASSIGNMENT_SUPERVISOR_ID,FL_SUP.ASSIGNMENT_ID) AS STRING)||'~'||FORMAT_DATE('%Y%m%d',COALESCE(PARSE_DATE('%Y-%m-%d',ASG_SUP.EFFECTIVE_START_DATE),FL_SUP.EFFECTIVE_START_DATE))||'~'||FORMAT_DATE('%Y%m%d',FL_SUP.EFFECTIVE_END_DATE) AS SOURCE_RECORD_ID               , 
  FL_SUP.ASSIGNMENT_ID AS ASSIGNMENT_ID                  , 
  COALESCE(FL_SUP.PERSON_ID ,-99999) AS PERSON_ID                      , 
  COALESCE(ASG_SUP.MANAGER_ASSIGNMENT_ID,-99999) AS MANAGER_ASSIGNMENT_ID          , 
  COALESCE(ASG_SUP.MANAGER_ID , -99999  ) AS MANAGER_ID                     , 
  ASG_SUP.ACTION_OCCURRENCE_ID AS ACTION_OCCURRENCE_ID           , 
  0 AS MANAGER_CHANGE_IND             , 
  -99999 AS PREVIOUS_MANAGER_ASSIGNMENT_ID , 
  -99999 AS PREVIOUS_MANAGER_ID            
 FROM  {{ ref('DW_WRKFRC_SUP_FL_DT_STAGE') }} FL_SUP 
 LEFT OUTER JOIN {{ ref('DW_WRKFRC_ASG_SUPERVISOR_F') }} ASG_SUP  ON 
 (FL_SUP.ASSIGNMENT_ID=ASG_SUP.ASSIGNMENT_ID AND 
 FL_SUP.EFFECTIVE_START_DATE=PARSE_DATE('%Y-%m-%d',ASG_SUP.EFFECTIVE_START_DATE)) 
  AND ASG_SUP.PRIMARY_FLAG = 'Y' AND ASG_SUP.MANAGER_TYPE = 'LINE_MANAGER'

