 SELECT  ASG_FTE_FL.ASSIGNMENT_ID AS ASSIGNMENT_ID         , 
  ASG_FTE_FL.EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE   , 
  $$$NEXT_VAL$$$(ASG_FTE_FL.EFFECTIVE_START_DATE-1,ASG_FTE_FL.EFFECTIVE_END_DATE) AS EFFECTIVE_END_DATE     
 FROM 'DW_WRKFRC_FTE_FL_DT_STAGE' ASG_FTE_FL

