 SELECT  ASG.ASSIGNMENT_ID AS ASSIGNMENT_ID        , 
  ASG.EFFECTIVE_START_DATE AS EVENT_DATE           , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE IN ('EMPL_WR_EMP','EMPL_ADD_EMP','EMPL_REHIRE','EMPL_ADD_CWK','EMPL_WR_CWK','EMPL_ADD_NWK','EMPL_ADD_PWK', 'EMPL_WR_NWK') THEN 1 ELSE 0 END) AS HIRE_EVENT_IND       , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE IN ('EMPL_REHIRE','EMPL_RENEW_CWK') THEN 1 ELSE 0    END) AS REHIRE_EVENT_IND     , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE = 'EMPL_PROMOTION' THEN 1 ELSE 0 END) AS PROMOTION_EVENT_IND  , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE = 'EMPL_TRANSFER'  THEN 1 ELSE 0 END) AS TRANSFER_EVENT_IND   , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE = 'EMPL_TERMINATE' THEN 1 ELSE 0 END) AS TERM_EVENT_IND       , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE = 'EMPL_TERMINATE' AND ACT.TERMINATION_TYPE = 'VOLUNTARY' THEN 1 ELSE 0 END) AS VOL_TERM_EVENT_IND   , 
  MAX(CASE WHEN ACT.ACTION_TYPE_CODE = 'EMPL_TERMINATE' AND ACT.TERMINATION_TYPE = 'IN_VOLUNTARY' THEN 1 ELSE 0 END) AS INVOL_TERM_EVENT_IND 
 FROM  {{ ref('DW_WRKFRC_ASG_F') }} ASG LEFT OUTER JOIN {{ ref('DW_ACTION_D') }} ACT  ON (ASG.ACTION_ID = ACT.ACTION_ID)
 WHERE  ACT.ACTION_TYPE_CODE IN ('EMPL_WR_EMP','EMPL_ADD_EMP','EMPL_REHIRE','EMPL_ADD_CWK','EMPL_WR_CWK','EMPL_RENEW_CWK','EMPL_PROMOTION','EMPL_TRANSFER','EMPL_TERMINATE','EMPL_ADD_NWK', 'EMPL_ADD_PWK','EMPL_WR_NWK') GROUP BY  ASG.ASSIGNMENT_ID, ASG.EFFECTIVE_START_DATE
