 SELECT     DW_MANAGER_DN_DH.MANAGER_ASSIGNMENT_ID AS MANAGER_ASSIGNMENT_ID           , 
     DW_MANAGER_DN_DH.MANAGER_ID AS MANAGER_ID                      , 
  COALESCE(DW_MANAGER_DRILLDOWN.MANAGER_ASSIGNMENT_ID,-99999) AS DRILLDOWN_MANAGER_ASSIGNMENT_ID        , 
  COALESCE(DW_MANAGER_DRILLDOWN.MANAGER_ID,-99999) AS DRILLDOWN_MANAGER_ID                   , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE AS CALENDAR_DATE                   , 
 --    DW_WRKFRC_ASG_DAY_SNAPSHOT_F.MANAGER_IND AS MANAGER_IND                     , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.DEPARTMENT_ID AS DEPARTMENT_ID                   , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.JOB_ID AS JOB_ID                          , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.JOB_FAMILY_ID AS JOB_FAMILY_ID                   , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LOCATION_ID AS LOCATION_ID                     , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.POSITION_ID AS POSITION_ID                     , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LEGAL_EMPLOYER_ID AS LEGAL_EMPLOYER_ID               , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.BUSINESS_UNIT_ID AS BUSINESS_UNIT_ID                , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ASSIGNMENT_STATUS_TYPE_ID AS ASSIGNMENT_STATUS_TYPE_ID       , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.WORKER_TYPE AS WORKER_TYPE                     , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.WORKER_CATEGORY AS WORKER_CATEGORY                 , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ASSIGNMENT_CATEGORY AS ASSIGNMENT_CATEGORY             , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LEGISLATION_CODE AS LEGISLATION_CODE                , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.COUNTRY AS COUNTRY                         , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.SEX AS SEX                             , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.MARITAL_STATUS AS MARITAL_STATUS                  , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.HIGHEST_EDUCATION_LEVEL AS HIGHEST_EDUCATION_LEVEL         , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ETHNICITY AS ETHNICITY                       , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.RELIGION AS RELIGION                        , 
  --   DW_WRKFRC_ASG_DAY_SNAPSHOT_F.DISABILITY_FLAG AS DISABILITY_FLAG                 , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.SYSTEM_PERSON_TYPE AS SYSTEM_PERSON_TYPE              , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.PAY_SYSTEM_STATUS AS PAY_SYSTEM_STATUS               , 
     DW_WRKFRC_ASG_DAY_SNAPSHOT_F.PER_SYSTEM_STATUS AS PER_SYSTEM_STATUS               , 
     DW_MANAGER_DN_DH.MANAGER_DISTANCE AS LEVEL_DISTANCE                  , 
     DW_MANAGER_DN_DH.MANAGER_ASSIGNMENT_ID||FORMAT_DATE('%Y%m%d',  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE) AS SOURCE_RECORD_ID                , 
     SUM(DW_WRKFRC_ASG_DAY_SNAPSHOT_F.HEADCOUNT) AS HEADCOUNT_NUMBER                , 
     SUM(DW_WRKFRC_ASG_DAY_SNAPSHOT_F.FTE) AS FTE_NUMBER                      , 
     COUNT(DW_MANAGER_DN_DH.ASSIGNMENT_ID) AS ASSIGNMENT_COUNT_NUMBER         
 FROM  {{ ref('DW_DAY_D') }} DAY_END INNER JOIN {{ ref('DW_OBJECT_LAST_LOAD_DATE') }} INRD  ON 1=1 
 AND INRD.OBJECT_NAME='DW_WRKFRC_SUPERVISOR_SNAPSHOT_F' AND DAY_END.CURRENT_CAL_DAY_CODE= 'Current'  
 INNER JOIN  {{ ref('DW_WRKFRC_ASG_SNAPSHOT_F') }} DW_WRKFRC_ASG_DAY_SNAPSHOT_F  ON 1=1 
 AND DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE<PARSE_DATE('%Y-%m-%d',DAY_END.CALENDAR_DATE) 
 AND DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE>=INRD.LAST_LOAD_DATE  
 INNER JOIN  {{ ref('DW_MANAGER_DN_DH') }} DW_MANAGER_DN_DH  ON ( DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ASSIGNMENT_ID = DW_MANAGER_DN_DH.ASSIGNMENT_ID 
 AND DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE BETWEEN PARSE_DATE('%Y-%m-%d',DW_MANAGER_DN_DH.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',DW_MANAGER_DN_DH.EFFECTIVE_END_DATE) 
 AND DW_MANAGER_DN_DH.PRIMARY_MANAGER_FLAG = 'Y' ) 
  LEFT OUTER JOIN  {{ ref('DW_MANAGER_DN_DH') }} DW_MANAGER_DRILLDOWN  ON ( 
      DW_MANAGER_DN_DH.MANAGER_ASSIGNMENT_ID = DW_MANAGER_DRILLDOWN.ASSIGNMENT_ID 
      AND DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE BETWEEN PARSE_DATE('%Y-%m-%d',DW_MANAGER_DRILLDOWN.EFFECTIVE_START_DATE) AND PARSE_DATE('%Y-%m-%d',DW_MANAGER_DRILLDOWN.EFFECTIVE_END_DATE) 
      AND DW_MANAGER_DRILLDOWN.PRIMARY_MANAGER_FLAG = 'Y' AND DW_MANAGER_DRILLDOWN.MANAGER_DISTANCE = 1)
 GROUP BY     DW_MANAGER_DN_DH.MANAGER_ASSIGNMENT_ID,    DW_MANAGER_DN_DH.MANAGER_ID, 
 COALESCE(DW_MANAGER_DRILLDOWN.MANAGER_ASSIGNMENT_ID,-99999), 
 COALESCE(DW_MANAGER_DRILLDOWN.MANAGER_ID,-99999),   
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE,   
--  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.MANAGER_IND,  
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.DEPARTMENT_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.JOB_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.JOB_FAMILY_ID,   
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LOCATION_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.POSITION_ID,   
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LEGAL_EMPLOYER_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.BUSINESS_UNIT_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ASSIGNMENT_STATUS_TYPE_ID,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.WORKER_TYPE,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.WORKER_CATEGORY,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ASSIGNMENT_CATEGORY,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.LEGISLATION_CODE,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.COUNTRY,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.SEX,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.MARITAL_STATUS,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.HIGHEST_EDUCATION_LEVEL,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.ETHNICITY,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.RELIGION,    
--  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.DISABILITY_FLAG,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.SYSTEM_PERSON_TYPE,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.PAY_SYSTEM_STATUS,    
  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.PER_SYSTEM_STATUS,    
  DW_MANAGER_DN_DH.MANAGER_DISTANCE,    
  DW_MANAGER_DN_DH.MANAGER_ASSIGNMENT_ID||FORMAT_DATE('%Y%m%d',  DW_WRKFRC_ASG_DAY_SNAPSHOT_F.CALENDAR_DATE)
