 SELECT  SUP.ASSIGNMENT_ID AS ASSIGNMENT_ID                  , 
  SUP.EFFECTIVE_END_DATE+1 AS EFFECTIVE_START_DATE           , 
  TO_CHAR(SUP.ASSIGNMENT_ID)||'~'||TO_CHAR((SUP.EFFECTIVE_END_DATE+1),'YYYYMMDD') AS SOURCE_RECORD_ID               , 
  SPASG.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE             , 
  'Y' AS COMPUTE_NEXT_DT_FLAG           , 
  SUP.PERSON_ID AS PERSON_ID                      
 FROM  {{ ref('DW_WRKFRC_ASG_SUPERVISOR_F') }} SUP INNER JOIN {{ ref('DW_WRKFRC_ASG_SPAN_DT_STAGE') }} SPASG  ON (SUP.ASSIGNMENT_ID=SPASG.ASSIGNMENT_ID)
 WHERE  NOT EXISTS(SELECT 1 FROM  DW_WRKFRC_ASG_SUPERVISOR_F SUPB WHERE SUP.ASSIGNMENT_ID=SUPB.ASSIGNMENT_ID AND SUP.EFFECTIVE_END_DATE+1 = SUPB.EFFECTIVE_START_DATE  ) AND SPASG.EFFECTIVE_END_DATE>SUP.EFFECTIVE_END_DATE
