 SELECT  FTE.ASSIGNWORKMEASUREID AS ASSIGN_WORK_MEASURE_ID , 
  FTE.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE   , 
  FTE.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE     , 
  TO_CHAR(FTE.ASSIGNWORKMEASUREID)||'~'||TO_CHAR(FTE.EFFECTIVESTARTDATE,'YYYYMMDD')||'~'||TO_CHAR(FTE.EFFECTIVEENDDATE,'YYYYMMDD') AS SOURCE_RECORD_ID       , 
  FTE.ASSIGNMENTWORKMEASUREPEOASSIGNMENTID AS ASSIGNMENT_ID          , 
  COALESCE(ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID,-99999) AS ACTION_OCCURRENCE_ID   , 
  COALESCE(ACTIONSPVO.ACTIONID,-99999) AS ACTION_ID              , 
  COALESCE(ACTIONREASONSPVO.ACTIONREASONID,-99999) AS ACTION_REASON_ID       , 
  FTE.ASSIGNMENTWORKMEASUREPEOVALUE AS FTE                    , 
  GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),FTE.EFFECTIVESTARTDATE) AS DW_DATE_FROM           , 
  FTE.EFFECTIVEENDDATE AS DW_DATE_TO             , 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') > FTE.EFFECTIVESTARTDATE  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND  
 FROM  {{ ref('stg_h_assignmentam_assignmentworkmeasurepvo') }} FTE 
      LEFT OUTER JOIN {{ ref('stg_h_actionam_actionoccurrencespvo') }} ACTIONOCCURRENCESPVO  ON FTE.ASSIGNMENTWORKMEASUREPEOACTIONOCCURRENCEID = ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionspvo') }} ACTIONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONID = ACTIONSPVO.ACTIONID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionreasonspvo') }} ACTIONREASONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONREASONID = ACTIONREASONSPVO.ACTIONREASONID
 WHERE  FTE.ASSIGNMENTWORKMEASUREPEOUNIT	= 'FTE'
