 SELECT  FTE_CHG.ASSIGN_WORK_MEASURE_ID AS ASSIGN_WORK_MEASURE_ID             , 
  FTE_CHG.EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE     , 
  FTE_CHG.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE         , 
  $$$PREVIOUS_CHANGE_IND$$$(FTE_CHG.FTE,FTE_CHG.FTE_CHANGE_IND) AS FTE_CHANGE_IND             , 
  $$$PREVIOUS_VAL$$$(FTE_CHG.FTE,FTE_CHG.PREVIOUS_FTE) AS PREVIOUS_FTE             
 FROM 'DW_WRKFRC_ASG_FTE_CHANGE_STAGE' FTE_CHG

