 SELECT  FTE.ASSIGNWORKMEASUREID AS ASSIGN_WORK_MEASURE_ID , 
  FTE.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE   , 
  FTE.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE     , 
  CAST(FTE.ASSIGNWORKMEASUREID AS STRING)||'~'||FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', FTE.EFFECTIVESTARTDATE)) ||'~'|| FORMAT_DATE('%Y%m%d', PARSE_DATE('%Y-%m-%d', FTE.EFFECTIVEENDDATE)) AS SOURCE_RECORD_ID       , 
  FTE.ASSIGNMENTWORKMEASUREPEOASSIGNMENTID AS ASSIGNMENT_ID          , 
  COALESCE(ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID,-99999) AS ACTION_OCCURRENCE_ID   , 
  COALESCE(ACTIONSPVO.ACTIONID,-99999) AS ACTION_ID              , 
  COALESCE(ACTIONREASONSPVO.ACTIONREASONID,-99999) AS ACTION_REASON_ID       , 
  FTE.ASSIGNMENTWORKMEASUREPEOVALUE AS FTE                    , 
  CASE WHEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') > PARSE_DATE('%Y-%m-%d', FTE.EFFECTIVESTARTDATE ) THEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') ELSE PARSE_DATE('%Y-%m-%d', FTE.EFFECTIVESTARTDATE) END AS DW_DATE_FROM, 
  FTE.EFFECTIVEENDDATE AS DW_DATE_TO             , 
  CASE WHEN PARSE_DATE('%Y-%m-%d', '{{ var("VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE") }}') > PARSE_DATE('%Y-%m-%d', FTE.EFFECTIVESTARTDATE)  THEN 1 ELSE 0 END  AS DW_INITIAL_RECORD_IND  
 FROM  {{ ref('stg_h_assignmentam_assignmentworkmeasurepvo') }} FTE 
      LEFT OUTER JOIN {{ ref('stg_h_actionam_actionoccurrencespvo') }} ACTIONOCCURRENCESPVO  ON FTE.ASSIGNMENTWORKMEASUREPEOACTIONOCCURRENCEID = ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionspvo') }} ACTIONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONID = ACTIONSPVO.ACTIONID 
      LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionreasonspvo') }} ACTIONREASONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONREASONID = ACTIONREASONSPVO.ACTIONREASONID
 WHERE  FTE.ASSIGNMENTWORKMEASUREPEOUNIT	= 'FTE'
