 SELECT  COALESCE(ASG_HDC.ASSIGN_WORK_MEASURE_ID,FL_HDC.ASSIGNMENT_ID) AS ASSIGN_WORK_MEASURE_ID , 
  COALESCE(ASG_HDC.EFFECTIVE_START_DATE,FL_HDC.EFFECTIVE_START_DATE) AS EFFECTIVE_START_DATE   , 
  FL_HDC.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE     , 
  TO_CHAR(COALESCE(ASG_HDC.ASSIGN_WORK_MEASURE_ID,-99999))||'~'||TO_CHAR(COALESCE(ASG_HDC.EFFECTIVE_START_DATE,FL_HDC.EFFECTIVE_START_DATE),'YYYYMMDD')||'~'||TO_CHAR(FL_HDC.EFFECTIVE_END_DATE,'YYYYMMDD') AS SOURCE_RECORD_ID       , 
  FL_HDC.ASSIGNMENT_ID AS ASSIGNMENT_ID          , 
  ASG_HDC.ACTION_OCCURRENCE_ID AS ACTION_OCCURRENCE_ID   , 
  ASG_HDC.HEADCOUNT AS HEADCOUNT              , 
  0 AS HEADCOUNT_CHANGE_IND   , 
  -99999 AS PREVIOUS_HEADCOUNT     
 FROM  {{ ref('DW_WRKFRC_HDC_FL_DT_STAGE') }} FL_HDC LEFT OUTER JOIN {{ ref('DW_WRKFRC_ASG_HEADCOUNT_F') }} ASG_HDC  ON (FL_HDC.ASSIGNMENT_ID=ASG_HDC.ASSIGNMENT_ID AND FL_HDC.EFFECTIVE_START_DATE=ASG_HDC.EFFECTIVE_START_DATE)

