 SELECT  ASG.ASSIGNMENTID AS ASSIGNMENT_ID                  , 
  TO_CHAR(ASG.ASSIGNMENTID) AS SOURCE_RECORD_ID               , 
  ASG.ASSIGNMENTPEOPERSONID AS PERSON_ID                      , 
  MIN(ASG.ASSIGNMENTPEOBUSINESSGROUPID) AS BUSINESS_GROUP_ID              , 
  MIN(ASG.ASSIGNMENTPEOASSIGNMENTTYPE) AS WORKER_TYPE                    , 
  CASE WHEN MIN(ASG.EFFECTIVESTARTDATE)>TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') THEN MIN(ASG.EFFECTIVESTARTDATE) ELSE TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') END AS EFFECTIVE_START_DATE           , 
  MAX(CASE WHEN ASGSTPVO.ASSIGNMENTSTATUSTYPESPEOPERSYSTEMSTATUS='INACTIVE' THEN ASG.EFFECTIVESTARTDATE-1 ELSE  ASG.EFFECTIVEENDDATE END) AS EFFECTIVE_END_DATE             
 FROM  {{ ref('stg_h_assignmentam_assignmentpvo') }} ASG INNER JOIN {{ ref('stg_h_assignmentam_assignmentstatustypespvo') }} ASGSTPVO  ON ASG.ASSIGNMENTPEOASSIGNMENTSTATUSTYPEID=ASGSTPVO.ASSIGNMENTSTATUSTYPEID
 WHERE  ASG.ASSIGNMENTPEOASSIGNMENTTYPE IN ('E','C','N','P') GROUP BY  ASG.ASSIGNMENTID, TO_CHAR(ASG.ASSIGNMENTID), ASG.ASSIGNMENTPEOPERSONID
