 SELECT  CDD.MANAGER_ASSIGNMENT_ID AS MANAGER_ASSIGNMENT_ID , 
  DRVD.ASSIGNMENT_ID AS ASSIGNMENT_ID         , 
  DRVD.EVENT_DATE AS EVENT_DATE            , 
  DRVD.EVENT_ID AS EVENT_ID              , 
  CAST(CDD.MANAGER_ASSIGNMENT_ID AS STRING)||'~'||CAST(DRVD.ASSIGNMENT_ID AS STRING)||'~'||FORMAT_DATE('%Y%m%d',DRVD.EVENT_DATE)||'~'||CAST(DRVD.EVENT_ID AS STRING) AS SOURCE_RECORD_ID      , 
  CASE WHEN SUM(DRVD.NET_GAIN_LOSS_IND) > 0 THEN 1 ELSE 0 END AS HRCHY_GAIN_IND        , 
  CASE WHEN SUM(DRVD.NET_GAIN_LOSS_IND) < 0 THEN 1 ELSE 0 END AS HRCHY_LOSS_IND        , 
  CASE WHEN SUM(DRVD.NET_GAIN_LOSS_IND) <> 0 THEN 1 ELSE 0 END AS HRCHY_IN_OUT_IND      
 FROM  {{ ref('DW_WRKFRC_ASG_GAIN_LOSS_DRVD_F') }} DRVD INNER JOIN {{ ref('DW_MANAGER_REPORTEES_CF_DN_DH') }} CDD  ON (CDD.LEVEL20_REPORTEE_ASSIGNMENT_ID=DRVD.ASSIGNMENT_ID AND DRVD.GAIN_LOSS_DATE BETWEEN CDD.EFFECTIVE_START_DATE AND  CDD.EFFECTIVE_END_DATE) AND CDD.MANAGER_DISTANCE <> 0
 GROUP BY  CDD.MANAGER_ASSIGNMENT_ID, DRVD.ASSIGNMENT_ID, DRVD.EVENT_DATE, DRVD.EVENT_ID,
  CAST(CDD.MANAGER_ASSIGNMENT_ID AS STRING)||'~'||CAST(DRVD.ASSIGNMENT_ID AS STRING)||'~'||FORMAT_DATE('%Y%m%d',DRVD.EVENT_DATE)||'~'||CAST(DRVD.EVENT_ID AS STRING)
