 SELECT  HDC.ASSIGNWORKMEASUREID AS ASSIGN_WORK_MEASURE_ID , 
  HDC.EFFECTIVESTARTDATE AS EFFECTIVE_START_DATE   , 
  HDC.EFFECTIVEENDDATE AS EFFECTIVE_END_DATE     , 
  TO_CHAR(HDC.ASSIGNWORKMEASUREID)||'~'||TO_CHAR(HDC.EFFECTIVESTARTDATE,'YYYYMMDD')||'~'||TO_CHAR(HDC.EFFECTIVESTARTDATE,'YYYYMMDD') AS SOURCE_RECORD_ID       , 
  HDC.ASSIGNMENTWORKMEASUREPEOASSIGNMENTID AS ASSIGNMENT_ID          , 
  COALESCE(ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID,-99999) AS ACTION_OCCURRENCE_ID   , 
  COALESCE(ACTIONSPVO.ACTIONID,-99999) AS ACTION_ID              , 
  COALESCE(ACTIONREASONSPVO.ACTIONREASONID,-99999) AS ACTION_REASON_ID       , 
  HDC.ASSIGNMENTWORKMEASUREPEOVALUE AS HEADCOUNT              , 
  GREATEST(TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS'),HDC.EFFECTIVESTARTDATE) AS DW_DATE_FROM           , 
  HDC.EFFECTIVEENDDATE AS DW_DATE_TO             , 
  CASE WHEN TO_DATE(SUBSTR('$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$',1,19),'YYYY-MM-DD HH24:MI:SS') > HDC.EFFECTIVESTARTDATE  THEN 1 ELSE 0 END AS DW_INITIAL_RECORD_IND  
 FROM  {{ ref('stg_h_assignmentam_assignmentworkmeasurepvo') }} HDC 
       LEFT OUTER JOIN {{ ref('stg_h_actionam_actionoccurrencespvo') }} ACTIONOCCURRENCESPVO  ON HDC.ASSIGNMENTWORKMEASUREPEOACTIONOCCURRENCEID = ACTIONOCCURRENCESPVO.ACTIONOCCURRENCEID 
       LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionspvo') }} ACTIONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONID = ACTIONSPVO.ACTIONID 
       LEFT OUTER JOIN  {{ ref('stg_h_actionam_actionreasonspvo') }} ACTIONREASONSPVO  ON ACTIONOCCURRENCESPVO.ACTIONOCCURRENCESPEOACTIONREASONID = ACTIONREASONSPVO.ACTIONREASONID
 WHERE  HDC.ASSIGNMENTWORKMEASUREPEOUNIT	= 'HEAD'
