 SELECT  HDF.ASSIGNMENT_ID AS ASSIGNMENT_ID                  , 
  HDF.EFFECTIVE_END_DATE+1 AS EFFECTIVE_START_DATE           , 
  TO_CHAR(HDF.ASSIGNMENT_ID)||'~'||TO_CHAR((HDF.EFFECTIVE_END_DATE+1),'YYYYMMDD') AS SOURCE_RECORD_ID               , 
  SPASG.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE             , 
  'Y' AS COMPUTE_NEXT_DT_FLAG           
 FROM  {{ ref('DW_WRKFRC_ASG_HEADCOUNT_F') }} HDF INNER JOIN {{ ref('DW_WRKFRC_ASG_SPAN_DT_STAGE') }} SPASG  ON (HDF.ASSIGNMENT_ID=SPASG.ASSIGNMENT_ID)
 WHERE  NOT EXISTS(SELECT 1 FROM  DW_WRKFRC_ASG_HEADCOUNT_F HCF WHERE HDF.ASSIGNMENT_ID=HCF.ASSIGNMENT_ID AND HDF.EFFECTIVE_END_DATE+1 = HCF.EFFECTIVE_START_DATE  ) AND SPASG.EFFECTIVE_END_DATE>HDF.EFFECTIVE_END_DATE
