 SELECT  CDD.MANAGER_ASSIGNMENT_ID AS MANAGER_ASSIGNMENT_ID , 
  GLF.ASSIGNMENT_ID AS ASSIGNMENT_ID         , 
  GLF.EVENT_DATE AS EVENT_DATE            , 
  GLF.EVENT_ID AS EVENT_ID              , 
  TO_CHAR(CDD.MANAGER_ASSIGNMENT_ID)||'~'||TO_CHAR(GLF.ASSIGNMENT_ID)||'~'||TO_CHAR(GLF.EVENT_DATE,'YYYYMMDD')||'~'||TO_CHAR(GLF.EVENT_ID) AS SOURCE_RECORD_ID      , 
  CASE WHEN SUM(GLF.NET_GAIN_LOSS_IND) = 0 THEN 1 ELSE 0 END AS HRCHY_CHNG_WTHN_IND   
 FROM  {{ ref('DW_WRKFRC_GAIN_LOSS_ASG_F') }} GLF INNER JOIN {{ ref('DW_MANAGER_REPORTEES_CF_DN_DH') }} CDD  ON (CDD.LEVEL20_REPORTEE_ASSIGNMENT_ID=GLF.ASSIGNMENT_ID AND GLF.GAIN_LOSS_DATE BETWEEN CDD.EFFECTIVE_START_DATE AND  CDD.EFFECTIVE_END_DATE) AND CDD.MANAGER_DISTANCE <> 0
 GROUP BY  CDD.MANAGER_ASSIGNMENT_ID, GLF.ASSIGNMENT_ID, GLF.EVENT_DATE, GLF.EVENT_ID, TO_CHAR(CDD.MANAGER_ASSIGNMENT_ID)||'~'||TO_CHAR(GLF.ASSIGNMENT_ID)||'~'||TO_CHAR(GLF.EVENT_DATE,'YYYYMMDD')||'~'||TO_CHAR(GLF.EVENT_ID)
