 SELECT  HDC_CHG.ASSIGN_WORK_MEASURE_ID AS ASSIGN_WORK_MEASURE_ID             , 
  HDC_CHG.EFFECTIVE_START_DATE AS EFFECTIVE_START_DATE     , 
  HDC_CHG.EFFECTIVE_END_DATE AS EFFECTIVE_END_DATE         , 
  $$$PREVIOUS_CHANGE_IND$$$(HDC_CHG.HEADCOUNT,HDC_CHG.HEADCOUNT_CHANGE_IND) AS HEADCOUNT_CHANGE_IND     , 
  $$$PREVIOUS_VAL$$$(HDC_CHG.HEADCOUNT,HDC_CHG.PREVIOUS_HEADCOUNT) AS PREVIOUS_HEADCOUNT         
 FROM 'DW_WRKFRC_ASG_HDC_CHANGE_STAGE' HDC_CHG

