 SELECT  ASG.ASSIGNMENTID AS ASSIGNMENT_ID                  , 
  CAST(ASG.ASSIGNMENTID AS STRING) AS SOURCE_RECORD_ID               , 
  ASG.ASSIGNMENTPEOPERSONID AS PERSON_ID                      , 
  MIN(ASG.ASSIGNMENTPEOBUSINESSGROUPID) AS BUSINESS_GROUP_ID              , 
  MIN(ASG.ASSIGNMENTPEOASSIGNMENTTYPE) AS WORKER_TYPE                    , 
  CASE WHEN MIN(PARSE_DATE('%Y-%m-%d',ASG.EFFECTIVESTARTDATE))> PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') THEN MIN(PARSE_DATE('%Y-%m-%d',ASG.EFFECTIVESTARTDATE)) ELSE PARSE_DATE('%Y-%m-%d', '$VAR_PARAM_GLOBAL_INITIAL_EXTRACT_DATE$') END AS EFFECTIVE_START_DATE           , 
  MAX(CASE WHEN ASGSTPVO.ASSIGNMENTSTATUSTYPESPEOPERSYSTEMSTATUS='INACTIVE' THEN PARSE_DATE('%Y-%m-%d',ASG.EFFECTIVESTARTDATE)-1 ELSE  PARSE_DATE('%Y-%m-%d',ASG.EFFECTIVEENDDATE) END) AS EFFECTIVE_END_DATE             
 FROM  {{ ref('stg_h_assignmentam_assignmentpvo') }} ASG INNER JOIN {{ ref('stg_h_assignmentam_assignmentstatustypespvo') }} ASGSTPVO  ON ASG.ASSIGNMENTPEOASSIGNMENTSTATUSTYPEID=ASGSTPVO.ASSIGNMENTSTATUSTYPEID
 WHERE  ASG.ASSIGNMENTPEOASSIGNMENTTYPE IN ('E','C','N','P') GROUP BY  ASG.ASSIGNMENTID, CAST(ASG.ASSIGNMENTID AS STRING), ASG.ASSIGNMENTPEOPERSONID
