with h_hcmprofilecontentlibraryam_ratingmodelfirstlangpvo as ( 
      select 
               RATINGMODELTRANSLATIONPEORATINGMODELID as RATINGMODELTRANSLATIONPEORATINGMODELID,
               LANGUAGE as LANGUAGE,
               RATINGMODELTRANSLATIONPEOBUSINESSGROUPID as RATINGMODELTRANSLATIONPEOBUSINESSGROUPID,
               SOURCELANG as SOURCELANG,
               RATINGMODELTRANSLATIONPEORATINGNAME as RATINGMODELTRANSLATIONPEORATINGNAME,
               RATINGMODELTRANSLATIONPEORATINGDESCRIPTION as RATINGMODELTRANSLATIONPEORATINGDESCRIPTION,
               RATINGMODELTRANSLATIONPEOLASTUPDATEDATE as RATINGMODELTRANSLATIONPEOLASTUPDATEDATE 
      from `chrome-genre-298014.sakra_stage.h_hcmprofilecontentlibraryam_ratingmodelfirstlangpvo`
)

select * from h_hcmprofilecontentlibraryam_ratingmodelfirstlangpvo
