with h_personam_personnamepvoviewall as ( 
      select 
               PERSONNAMEID as PERSONNAMEID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               PERSONNAMEPEOPERSONID as PERSONNAMEPEOPERSONID,
               PERSONNAMEPEOBUSINESSGROUPID as PERSONNAMEPEOBUSINESSGROUPID,
               PERSONNAMEPEOLEGISLATIONCODE as PERSONNAMEPEOLEGISLATIONCODE,
               PERSONNAMEPEONAMETYPE as PERSONNAMEPEONAMETYPE,
               PERSONNAMEPEODISPLAYNAME as PERSONNAMEPEODISPLAYNAME,
               PERSONNAMEPEOFIRSTNAME as PERSONNAMEPEOFIRSTNAME,
               PERSONNAMEPEOLASTNAME as PERSONNAMEPEOLASTNAME,
               PERSONNAMEPEOMIDDLENAMES as PERSONNAMEPEOMIDDLENAMES,
               PERSONNAMEPEOTITLE as PERSONNAMEPEOTITLE,
               PERSONNAMEPEOPRENAMEADJUNCT as PERSONNAMEPEOPRENAMEADJUNCT,
               PERSONNAMEPEOSUFFIX as PERSONNAMEPEOSUFFIX,
               PERSONNAMEPEOKNOWNAS as PERSONNAMEPEOKNOWNAS,
               PERSONNAMEPEOPREVIOUSLASTNAME as PERSONNAMEPEOPREVIOUSLASTNAME,
               PERSONNAMEPEOFULLNAME as PERSONNAMEPEOFULLNAME,
               PERSONNAMEPEOLISTNAME as PERSONNAMEPEOLISTNAME,
               PERSONNAMEPEOORDERNAME as PERSONNAMEPEOORDERNAME,
               PERSONNAMEPEOCREATIONDATE as PERSONNAMEPEOCREATIONDATE,
               PERSONNAMEPEOLASTUPDATEDATE as PERSONNAMEPEOLASTUPDATEDATE,
      from 'chrome-genre-298014.sakra_stage.h_personam_personnamepvoviewall'
)

select * from h_personam_personnamepvoviewall
