with h_personam_personethinicitypvoviewall as ( 
      select 
               ETHNICITYID as ETHNICITYID,
               ETHNICITYPEOPERSONID as ETHNICITYPEOPERSONID,
               ETHNICITYPEOBUSINESSGROUPID as ETHNICITYPEOBUSINESSGROUPID,
               ETHNICITYPEOLEGISLATIONCODE as ETHNICITYPEOLEGISLATIONCODE,
               ETHNICITYPEOETHNICITY as ETHNICITYPEOETHNICITY,
               ETHNICITYPEOPRIMARYFLAG as ETHNICITYPEOPRIMARYFLAG,
               ETHNICITYPEOCREATIONDATE as ETHNICITYPEOCREATIONDATE,
               ETHNICITYPEOLASTUPDATEDATE as ETHNICITYPEOLASTUPDATEDATE 
      from 'chrome-genre-298014.sakra_stage.h_personam_personethinicitypvoviewall'
)

select * from h_personam_personethinicitypvoviewall
