with h_locationam_hrlocationspvo as ( 
      select 
               LOCATIONDETAILSID as LOCATIONDETAILSID,
               LOCATIONPEOLOCATIONID as LOCATIONPEOLOCATIONID,
               LOCATIONPEOINTERNALLOCATIONCODE as LOCATIONPEOINTERNALLOCATIONCODE,
               ADDRESSESPEOADDRESSLINE1 as ADDRESSESPEOADDRESSLINE1,
               ADDRESSESPEOADDRESSLINE2 as ADDRESSESPEOADDRESSLINE2,
               ADDRESSESPEOADDRESSLINE3 as ADDRESSESPEOADDRESSLINE3,
               ADDRESSESPEOADDRESSLINE4 as ADDRESSESPEOADDRESSLINE4,
               ADDRESSESPEOTOWNORCITY as ADDRESSESPEOTOWNORCITY,
               ADDRESSESPEOPOSTALCODE as ADDRESSESPEOPOSTALCODE,
               ADDRESSESPEOREGION1 as ADDRESSESPEOREGION1,
               ADDRESSESPEOREGION2 as ADDRESSESPEOREGION2,
               ADDRESSESPEOREGION3 as ADDRESSESPEOREGION3,
               ADDRESSESPEOCOUNTRY as ADDRESSESPEOCOUNTRY,
               LOCATIONDETAILSPEOTELEPHONENUMBER1 as LOCATIONDETAILSPEOTELEPHONENUMBER1,
               LOCATIONDETAILSPEOMAINPHONEEXTENSION1 as LOCATIONDETAILSPEOMAINPHONEEXTENSION1,
               LOCATIONDETAILSPEOTELEPHONENUMBER2 as LOCATIONDETAILSPEOTELEPHONENUMBER2,
               LOCATIONDETAILSPEOFAXEXTENSION2 as LOCATIONDETAILSPEOFAXEXTENSION2,
               LOCATIONDETAILSPEOTELEPHONENUMBER3 as LOCATIONDETAILSPEOTELEPHONENUMBER3,
               LOCATIONDETAILSPEOOTHERPHONEEXTENSION3 as LOCATIONDETAILSPEOOTHERPHONEEXTENSION3,
               LOCATIONDETAILSPEOEMAILADDRESS as LOCATIONDETAILSPEOEMAILADDRESS,
               LOCATIONDETAILSPEOACTIVESTATUS as LOCATIONDETAILSPEOACTIVESTATUS,
               INVENTORYORGANIZATIONPEOORGANIZATIONNAME as INVENTORYORGANIZATIONPEOORGANIZATIONNAME,
               ADDRESSESPEOLASTUPDATEDATE as ADDRESSESPEOLASTUPDATEDATE,
               LOCATIONDETAILSPEOLASTUPDATEDATE as LOCATIONDETAILSPEOLASTUPDATEDATE,
               LOCATIONPEOLASTUPDATEDATE as LOCATIONPEOLASTUPDATEDATE,
      from 'chrome-genre-298014.sakra_stage.h_locationam_hrlocationspvo'
)

select * from h_locationam_hrlocationspvo
