with h_personsdffbiam_flex_bi_personsdff_vi as ( 
      select 
               S_K_5000 as S_K_5000,
               APPLICATIONID as APPLICATIONID,
               FLEXFIELDCODE as FLEXFIELDCODE,
               CDC_PERSON_GLB_ as CDC_PERSON_GLB_,
               CDC_PERSON_GLB_C as CDC_PERSON_GLB_C,
               CDC_TEST_SEGMENT1_ as CDC_TEST_SEGMENT1_,
               CDC_TEST_SEGMENT1_C as CDC_TEST_SEGMENT1_C,
               FBLPG_ as FBLPG_,
               FBLPG_C as FBLPG_C,
               PERSONS_1_ as PERSONS_1_,
               PERSONS_1_C as PERSONS_1_C,
               PERSON_SEGMENT_1_ as PERSON_SEGMENT_1_,
               PERSON_SEGMENT_1_C as PERSON_SEGMENT_1_C,
               PERSON_GLB_ as PERSON_GLB_,
               PERSON_GLB_C as PERSON_GLB_C,
               FLEX_CONTEXT_ as FLEX_CONTEXT_,
               TESTG_ as TESTG_,
               TESTG_C as TESTG_C,
               CRFL_CONTEXT_SEGMENT_ as CRFL_CONTEXT_SEGMENT_,
               CRFL_CONTEXT_SEGMENT_C as CRFL_CONTEXT_SEGMENT_C,
               CR_NSRNC_LGBL_ as CR_NSRNC_LGBL_,
               CR_NSRNC_LGBL_C as CR_NSRNC_LGBL_C,
               CR_NSRNC_PLCY_NBR_ as CR_NSRNC_PLCY_NBR_,
               CR_NSRNC_PLCY_NBR_C as CR_NSRNC_PLCY_NBR_C,
               CR_NSRNC_PRFTR_ as CR_NSRNC_PRFTR_,
               CR_NSRNC_PRFTR_C as CR_NSRNC_PRFTR_C,
               PERSON_CNTX_ as PERSON_CNTX_,
               PERSON_CNTX_C as PERSON_CNTX_C,
               CREATIONDATE as CREATIONDATE,
               CREATEDBY as CREATEDBY,
               LASTUPDATEDATE as LASTUPDATEDATE,
               LASTUPDATEDBY as LASTUPDATEDBY,
               NAME_FLEX_CONTEXT_ as NAME_FLEX_CONTEXT_,
               DESC_FLEX_CONTEXT_ as DESC_FLEX_CONTEXT_,
               KEY_FLEX_CONTEXT_0 as KEY_FLEX_CONTEXT_0,
               KEY_FLEX_CONTEXT_1 as KEY_FLEX_CONTEXT_1,
               KEY_FLEX_CONTEXT_2 as KEY_FLEX_CONTEXT_2,
               DESC_CR_NSRNC_LGBL_ as DESC_CR_NSRNC_LGBL_,
               KEY_CR_NSRNC_LGBL_0 as KEY_CR_NSRNC_LGBL_0 
      from 'chrome-genre-298014.sakra_stage.h_personsdffbiam_flex_bi_personsdff_vi'
)

select * from h_personsdffbiam_flex_bi_personsdff_vi
