with h_assignmentam_assignmentworkmeasurepvo as ( 
      select 
               ASSIGNWORKMEASUREID as ASSIGNWORKMEASUREID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               ASSIGNMENTWORKMEASUREPEOASSIGNMENTID as ASSIGNMENTWORKMEASUREPEOASSIGNMENTID,
               ASSIGNMENTWORKMEASUREPEOACTIONOCCURRENCEID as ASSIGNMENTWORKMEASUREPEOACTIONOCCURRENCEID,
               ASSIGNMENTWORKMEASUREPEOBUSINESSGROUPID as ASSIGNMENTWORKMEASUREPEOBUSINESSGROUPID,
               ASSIGNMENTWORKMEASUREPEOUNIT as ASSIGNMENTWORKMEASUREPEOUNIT,
               ASSIGNMENTWORKMEASUREPEOVALUE as ASSIGNMENTWORKMEASUREPEOVALUE,
               ASSIGNMENTWORKMEASUREPEOLASTUPDATELOGIN as ASSIGNMENTWORKMEASUREPEOLASTUPDATELOGIN,
               ASSIGNMENTWORKMEASUREPEOCREATEDBY as ASSIGNMENTWORKMEASUREPEOCREATEDBY,
               ASSIGNMENTWORKMEASUREPEOCREATIONDATE as ASSIGNMENTWORKMEASUREPEOCREATIONDATE,
               ASSIGNMENTWORKMEASUREPEOLASTUPDATEDBY as ASSIGNMENTWORKMEASUREPEOLASTUPDATEDBY,
               ASSIGNMENTWORKMEASUREPEOLASTUPDATEDATE as ASSIGNMENTWORKMEASUREPEOLASTUPDATEDATE,
      from 'chrome-genre-298014.sakra_stage.h_assignmentam_assignmentworkmeasurepvo'
)

select * from h_assignmentam_assignmentworkmeasurepvo
