with f_finxlaamssetupslamam_acctgmethodpvo as ( 
      select 
               ACCTGMETHODTRANSLATIONACCOUNTINGMETHODTYPECODE as ACCTGMETHODTRANSLATIONACCOUNTINGMETHODTYPECODE,
               ACCTGMETHODTRANSLATIONACCOUNTINGMETHODCODE as ACCTGMETHODTRANSLATIONACCOUNTINGMETHODCODE,
               ACCTGMETHODTRANSLATIONLANGUAGE as ACCTGMETHODTRANSLATIONLANGUAGE,
               ACCTGMETHODTRANSLATIONNAME as ACCTGMETHODTRANSLATIONNAME,
               ACCTGMETHODTRANSLATIONDESCRIPTION as ACCTGMETHODTRANSLATIONDESCRIPTION,
               ACCTGMETHODTRANSLATIONSOURCELANG as ACCTGMETHODTRANSLATIONSOURCELANG,
               ACCTGMETHODTRANSLATIONLASTUPDATEDATE as ACCTGMETHODTRANSLATIONLASTUPDATEDATE,
               ACCTGMETHODTRANSLATIONLASTUPDATEDBY as ACCTGMETHODTRANSLATIONLASTUPDATEDBY,
               ACCTGMETHODTRANSLATIONCREATIONDATE as ACCTGMETHODTRANSLATIONCREATIONDATE,
               ACCTGMETHODTRANSLATIONCREATEDBY as ACCTGMETHODTRANSLATIONCREATEDBY 
      from `chrome-genre-298014.sakra_stage.f_finxlaamssetupslamam_acctgmethodpvo`
)

select * from f_finxlaamssetupslamam_acctgmethodpvo
