with f_finglledgerdefnam_ledgerpvo as ( 
      select 
               LEDGERID as LEDGERID,
               LEDGERNAME as LEDGERNAME,
               LEDGERSHORTNAME as LEDGERSHORTNAME,
               LEDGERACCOUNTEDPERIODTYPE as LEDGERACCOUNTEDPERIODTYPE,
               LEDGERCHARTOFACCOUNTSID as LEDGERCHARTOFACCOUNTSID,
               LEDGERCREATEDBY as LEDGERCREATEDBY,
               LEDGERCREATIONDATE as LEDGERCREATIONDATE,
               LEDGERCURRENCYCODE as LEDGERCURRENCYCODE,
               LEDGERDESCRIPTION as LEDGERDESCRIPTION,
               LEDGERLASTUPDATEDATE as LEDGERLASTUPDATEDATE,
               LEDGERLASTUPDATEDBY as LEDGERLASTUPDATEDBY,
               LEDGERLEDGERCATEGORYCODE as LEDGERLEDGERCATEGORYCODE,
               LEDGERPERIODSETNAME as LEDGERPERIODSETNAME,
               LEDGERSLAACCOUNTINGMETHODTYPE as LEDGERSLAACCOUNTINGMETHODTYPE,
               LEDGERSLAACCOUNTINGMETHODCODE as LEDGERSLAACCOUNTINGMETHODCODE,
               GLCALENDARSPERIODSETNAME as GLCALENDARSPERIODSETNAME,
               GLCALENDARSPERIODTYPE as GLCALENDARSPERIODTYPE,
               CURRENCYCURRENCYCODE as CURRENCYCURRENCYCODE 
      from `chrome-genre-298014.sakra_stage.f_finglledgerdefnam_ledgerpvo`
)

select * from f_finglledgerdefnam_ledgerpvo
