with h_gradeam_gradepvo as ( 
      select 
               GRADEID as GRADEID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               GRADEPEOBUSINESSGROUPID as GRADEPEOBUSINESSGROUPID,
               GRADEPEOCEILINGSTEPID as GRADEPEOCEILINGSTEPID,
               GRADEPEOCREATEDBY as GRADEPEOCREATEDBY,
               GRADEPEOACTIONOCCURRENCEID as GRADEPEOACTIONOCCURRENCEID,
               GRADEPEOACTIVESTATUS as GRADEPEOACTIVESTATUS,
               GRADEPEOCREATIONDATE as GRADEPEOCREATIONDATE,
               GRADEPEOGRADECODE as GRADEPEOGRADECODE,
               GRADEPEOGRADETYPE as GRADEPEOGRADETYPE,
               GRADEPEOLASTUPDATEDATE as GRADEPEOLASTUPDATEDATE,
               GRADEPEOLASTUPDATELOGIN as GRADEPEOLASTUPDATELOGIN,
               GRADEPEOLASTUPDATEDBY as GRADEPEOLASTUPDATEDBY,
               GRADEPEOOBJECTVERSIONNUMBER as GRADEPEOOBJECTVERSIONNUMBER,
               GRADEPEOPAYSCALEID as GRADEPEOPAYSCALEID,
               GRADEPEOSETID as GRADEPEOSETID,
               GRADEPEOSTARTINGSTEP as GRADEPEOSTARTINGSTEP 
      from 'chrome-genre-298014.sakra_stage.h_gradeam_gradepvo'
)

select * from h_gradeam_gradepvo
