with h_hcmprofilecontentlibraryam_ratingcategoriesfirstpvo as ( 
      select 
               RATINGCATEGORIESBPEOBUSINESSGROUPID as RATINGCATEGORIESBPEOBUSINESSGROUPID,
               RATINGCATEGORIESBPEOCATEGORYID as RATINGCATEGORIESBPEOCATEGORYID,
               CREATEDBY as CREATEDBY,
               CREATIONDATE as CREATIONDATE,
               LASTUPDATEDATE as LASTUPDATEDATE,
               LASTUPDATELOGIN as LASTUPDATELOGIN,
               LASTUPDATEDBY as LASTUPDATEDBY,
               RATINGCATEGORIESBPEOLOWERBOUNDARY as RATINGCATEGORIESBPEOLOWERBOUNDARY,
               RATINGCATEGORIESBPEOMODULEID as RATINGCATEGORIESBPEOMODULEID,
               OBJECTVERSIONNUMBER as OBJECTVERSIONNUMBER,
               RATINGCATEGORIESBPEORATINGMODELID as RATINGCATEGORIESBPEORATINGMODELID,
               RATINGCATEGORIESBPEOUPPERBOUNDARY as RATINGCATEGORIESBPEOUPPERBOUNDARY,
      from 'chrome-genre-298014.sakra_stage.h_hcmprofilecontentlibraryam_ratingcategoriesfirstpvo'
)

select * from h_hcmprofilecontentlibraryam_ratingcategoriesfirstpvo
