with h_hcmprofilecontentlibraryam_ratingcategoriesfirstlangpvo as ( 
      select 
               RATINGCATEGORIESTRANSLATIONPEOCATEGORYID as RATINGCATEGORIESTRANSLATIONPEOCATEGORYID,
               RATINGCATEGORIESTRANSLATIONPEOLANGUAGE as RATINGCATEGORIESTRANSLATIONPEOLANGUAGE,
               RATINGCATEGORIESTRANSLATIONPEOBUSINESSGROUPID as RATINGCATEGORIESTRANSLATIONPEOBUSINESSGROUPID,
               RATINGCATEGORIESTRANSLATIONPEOCATEGORYDESCRIPTION as RATINGCATEGORIESTRANSLATIONPEOCATEGORYDESCRIPTION,
               RATINGCATEGORIESTRANSLATIONPEOCATEGORYNAME as RATINGCATEGORIESTRANSLATIONPEOCATEGORYNAME,
               SOURCELANG as SOURCELANG,
               RATINGCATEGORIESTRANSLATIONPLASTUPDATEDATE as RATINGCATEGORIESTRANSLATIONPLASTUPDATEDATE 
      from `chrome-genre-298014.sakra_stage.h_hcmprofilecontentlibraryam_ratingcategoriesfirstlangpvo`
)

select * from h_hcmprofilecontentlibraryam_ratingcategoriesfirstlangpvo
