with f_fingljrnlsetupsrcam_journalsourcebpvo as ( 
      select 
               JESOURCENAME as JESOURCENAME,
               JRNLSRCLASTUPDATEDATE as JRNLSRCLASTUPDATEDATE,
               JRNLSRCTRANSLATEDCREATEDBY as JRNLSRCTRANSLATEDCREATEDBY,
               JRNLSRCTRANSLATEDCREATIONDATE as JRNLSRCTRANSLATEDCREATIONDATE,
               JRNLSRCTRANSLATEDDESCRIPTION as JRNLSRCTRANSLATEDDESCRIPTION,
               JRNLSRCTRANSLATEDJESOURCENAME as JRNLSRCTRANSLATEDJESOURCENAME,
               JRNLSRCTRANSLATEDLANGUAGE as JRNLSRCTRANSLATEDLANGUAGE,
               JRNLSRCTRANSLATEDLASTUPDATEDATE as JRNLSRCTRANSLATEDLASTUPDATEDATE,
               JRNLSRCTRANSLATEDLASTUPDATEDBY as JRNLSRCTRANSLATEDLASTUPDATEDBY,
               JRNLSRCTRANSLATEDSOURCELANG as JRNLSRCTRANSLATEDSOURCELANG,
               JRNLSRCTRANSLATEDUSERJESOURCENAME as JRNLSRCTRANSLATEDUSERJESOURCENAME 
      from 'chrome-genre-298014.sakra_stage.f_fingljrnlsetupsrcam_journalsourcebpvo'
)

select * from f_fingljrnlsetupsrcam_journalsourcebpvo
