with h_gradeam_ratepvo as ( 
      select 
               RATEID as RATEID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               RATEPEORATETYPE as RATEPEORATETYPE,
               RATEPEORATEOBJECTTYPE as RATEPEORATEOBJECTTYPE,
               RATEPEORATEUOM as RATEPEORATEUOM,
               RATEPEORATEFREQUENCY as RATEPEORATEFREQUENCY,
               RATEPEOPAYSCALEID as RATEPEOPAYSCALEID,
               RATEPEOACTIONOCCURRENCEID as RATEPEOACTIONOCCURRENCEID,
               RATEPEOACTIVESTATUS as RATEPEOACTIVESTATUS,
               RATEPEOANNUALIZATIONFACTOR as RATEPEOANNUALIZATIONFACTOR,
               RATEPEOCREATEDBY as RATEPEOCREATEDBY,
               RATEPEOCREATIONDATE as RATEPEOCREATIONDATE,
               RATEPEOCURRENCYCODE as RATEPEOCURRENCYCODE,
               RATEPEOGRADELADDERID as RATEPEOGRADELADDERID,
               RATEPEOLASTUPDATEDATE as RATEPEOLASTUPDATEDATE,
               RATEPEOLASTUPDATELOGIN as RATEPEOLASTUPDATELOGIN,
               RATEPEOLASTUPDATEDBY as RATEPEOLASTUPDATEDBY,
               RATEPEOLEGISLATIONCODE as RATEPEOLEGISLATIONCODE,
               RATEPEOLEGISLATIVEDATAGROUPID as RATEPEOLEGISLATIVEDATAGROUPID,
               RATEPEOOBJECTVERSIONNUMBER as RATEPEOOBJECTVERSIONNUMBER,
               RATEPEOPROGRESSIONRATEFLAG as RATEPEOPROGRESSIONRATEFLAG,
      from 'chrome-genre-298014.sakra_stage.h_gradeam_ratepvo'
)

select * from h_gradeam_ratepvo
