with h_useram_userpvo as ( 
      select 
               USERPEOUSERID as USERPEOUSERID,
               USERPEOACTIVEFLAG as USERPEOACTIVEFLAG,
               USERPEOHRTERMINATED as USERPEOHRTERMINATED,
               USERPEOSUSPENDED as USERPEOSUSPENDED,
               USERPEOUSERGUID as USERPEOUSERGUID,
               USERPEOUSERNAME as USERPEOUSERNAME,
               USERPEOPERSONID as USERPEOPERSONID,
               USERPEOSTARTDATE as USERPEOSTARTDATE,
               USERPEOENDDATE as USERPEOENDDATE,
               USERPEOCREATIONDATE as USERPEOCREATIONDATE,
               USERPEOCREATEDBY as USERPEOCREATEDBY,
               USERPEOLASTUPDATEDATE as USERPEOLASTUPDATEDATE,
               USERPEOLASTUPDATELOGIN as USERPEOLASTUPDATELOGIN,
               USERPEOLASTUPDATEDBY as USERPEOLASTUPDATEDBY 
      from 'chrome-genre-298014.sakra_stage.h_useram_userpvo'
)

select * from h_useram_userpvo
