with h_hcmprofilecontentlibraryam_ratinglevelfirstpvo as ( 
      select 
               RATINGLEVELBPEORATINGLEVELID as RATINGLEVELBPEORATINGLEVELID,
               RATINGLEVELBPEOBUSINESSGROUPID as RATINGLEVELBPEOBUSINESSGROUPID,
               RATINGLEVELBPEORATINGMODELID as RATINGLEVELBPEORATINGMODELID,
               RATINGLEVELBPEORATINGLEVELCODE as RATINGLEVELBPEORATINGLEVELCODE,
               RATINGLEVELBPEODATEFROM as RATINGLEVELBPEODATEFROM,
               RATINGLEVELBPEODATETO as RATINGLEVELBPEODATETO,
               RATINGLEVELBPEOCAREERSTRDEV as RATINGLEVELBPEOCAREERSTRDEV,
               RATINGLEVELBPEOREVIEWPOINTS as RATINGLEVELBPEOREVIEWPOINTS,
               RATINGLEVELBPEONUMERICRATING as RATINGLEVELBPEONUMERICRATING,
               RATINGLEVELBPEOFROMPOINTS as RATINGLEVELBPEOFROMPOINTS,
               RATINGLEVELBPEOTOPOINTS as RATINGLEVELBPEOTOPOINTS,
               OBJECTVERSIONNUMBER as OBJECTVERSIONNUMBER,
               CREATEDBY as CREATEDBY,
               CREATIONDATE as CREATIONDATE,
               LASTUPDATEDATE as LASTUPDATEDATE,
               LASTUPDATEDBY as LASTUPDATEDBY,
               LASTUPDATELOGIN as LASTUPDATELOGIN,
               RATINGLEVELBPEOMODULEID as RATINGLEVELBPEOMODULEID,
               RATINGLEVELBPEOSTARRATING as RATINGLEVELBPEOSTARRATING,
               RATINGLEVELBPEOMINRATINGDISTRIBUTION as RATINGLEVELBPEOMINRATINGDISTRIBUTION,
               RATINGLEVELBPEOMAXRATINGDISTRIBUTION as RATINGLEVELBPEOMAXRATINGDISTRIBUTION 
      from `chrome-genre-298014.sakra_stage.h_hcmprofilecontentlibraryam_ratinglevelfirstpvo`
)

select * from h_hcmprofilecontentlibraryam_ratinglevelfirstpvo
