with h_compensationam_salarybasespvo as ( 
      select 
               SALARYBASESTLPEOSALARYBASISID as SALARYBASESTLPEOSALARYBASISID,
               SALARYBASESTLPEOLANGUAGE as SALARYBASESTLPEOLANGUAGE,
               SALARYBASESTLPEOSALARYBASISNAME as SALARYBASESTLPEOSALARYBASISNAME,
               SALARYBASESTLPEODESCRIPTION as SALARYBASESTLPEODESCRIPTION,
               SALARYBASESTLPEOCREATEDBY as SALARYBASESTLPEOCREATEDBY,
               SALARYBASESTLPEOCREATIONDATE as SALARYBASESTLPEOCREATIONDATE,
               SALARYBASESTLPEOLASTUPDATEDBY as SALARYBASESTLPEOLASTUPDATEDBY,
               SALARYBASESTLPEOLASTUPDATEDATE as SALARYBASESTLPEOLASTUPDATEDATE,
      from 'chrome-genre-298014.sakra_stage.h_compensationam_salarybasespvo'
)

select * from h_compensationam_salarybasespvo
