with h_gradeam_ratevaluepvo as ( 
      select 
               RATEVALUEID as RATEVALUEID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               RATEVALUEPEOACTIONOCCURRENCEID as RATEVALUEPEOACTIONOCCURRENCEID,
               RATEVALUEPEOLEGISLATIONCODE as RATEVALUEPEOLEGISLATIONCODE,
               RATEVALUEPEOMAXIMUM as RATEVALUEPEOMAXIMUM,
               RATEVALUEPEOMIDVALUE as RATEVALUEPEOMIDVALUE,
               RATEVALUEPEOMINIMUM as RATEVALUEPEOMINIMUM,
               RATEVALUEPEORATEID as RATEVALUEPEORATEID,
               RATEVALUEPEORATEOBJECTTYPE as RATEVALUEPEORATEOBJECTTYPE,
               RATEVALUEPEORATEOBJECTID as RATEVALUEPEORATEOBJECTID,
               RATEVALUEPEOSEQUENCE as RATEVALUEPEOSEQUENCE,
               RATEVALUEPEOVALUE as RATEVALUEPEOVALUE,
               RATEVALUEPEOCREATEDBY as RATEVALUEPEOCREATEDBY,
               RATEVALUEPEOCREATIONDATE as RATEVALUEPEOCREATIONDATE,
               RATEVALUEPEOLASTUPDATEDATE as RATEVALUEPEOLASTUPDATEDATE,
               RATEVALUEPEOLASTUPDATELOGIN as RATEVALUEPEOLASTUPDATELOGIN,
               RATEVALUEPEOLASTUPDATEDBY as RATEVALUEPEOLASTUPDATEDBY,
               RATEVALUEPEOOBJECTVERSIONNUMBER as RATEVALUEPEOOBJECTVERSIONNUMBER 
      from `chrome-genre-298014.sakra_stage.h_gradeam_ratevaluepvo`
)

select * from h_gradeam_ratevaluepvo
