with h_personam_personpvo as ( 
      select 
               PERSONID as PERSONID,
               PERSONPEOBUSINESSGROUPID as PERSONPEOBUSINESSGROUPID,
               PERSONPEOSTARTDATE as PERSONPEOSTARTDATE,
               PERSONPEOCORRESPONDENCELANGUAGE as PERSONPEOCORRESPONDENCELANGUAGE,
               PERSONPEODATEOFBIRTH as PERSONPEODATEOFBIRTH,
               PERSONPEODATEOFDEATH as PERSONPEODATEOFDEATH,
               PERSONPEOCOUNTRYOFBIRTH as PERSONPEOCOUNTRYOFBIRTH,
               PERSONPEOREGIONOFBIRTH as PERSONPEOREGIONOFBIRTH,
               PERSONPEOTOWNOFBIRTH as PERSONPEOTOWNOFBIRTH,
               PERSONPEOBLOODTYPE as PERSONPEOBLOODTYPE,
               PERSONPEOCREATIONDATE as PERSONPEOCREATIONDATE,
               PERSONPEOLASTUPDATEDATE as PERSONPEOLASTUPDATEDATE 
      from 'chrome-genre-298014.sakra_stage.h_personam_personpvo'
)

select * from h_personam_personpvo
