with h_assignmentam_assignmentsupervisorpvo as ( 
      select 
               ASSIGNMENTSUPERVISORID as ASSIGNMENTSUPERVISORID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               ASSIGNMENTSUPERVISORPEOACTIONOCCURRENCEID as ASSIGNMENTSUPERVISORPEOACTIONOCCURRENCEID,
               ASSIGNMENTSUPERVISORPEOASSIGNMENTID as ASSIGNMENTSUPERVISORPEOASSIGNMENTID,
               ASSIGNMENTSUPERVISORPEOBUSINESSGROUPID as ASSIGNMENTSUPERVISORPEOBUSINESSGROUPID,
               ASSIGNMENTSUPERVISORPEOMANAGERASSIGNMENTID as ASSIGNMENTSUPERVISORPEOMANAGERASSIGNMENTID,
               ASSIGNMENTSUPERVISORPEOMANAGERID as ASSIGNMENTSUPERVISORPEOMANAGERID,
               ASSIGNMENTSUPERVISORPEOMANAGERTYPE as ASSIGNMENTSUPERVISORPEOMANAGERTYPE,
               ASSIGNMENTSUPERVISORPEOPERSONID as ASSIGNMENTSUPERVISORPEOPERSONID,
               ASSIGNMENTSUPERVISORPEOPRIMARYFLAG as ASSIGNMENTSUPERVISORPEOPRIMARYFLAG,
               ASSIGNMENTSUPERVISORPEOLASTUPDATELOGIN as ASSIGNMENTSUPERVISORPEOLASTUPDATELOGIN,
               ASSIGNMENTSUPERVISORPEOCREATEDBY as ASSIGNMENTSUPERVISORPEOCREATEDBY,
               ASSIGNMENTSUPERVISORPEOCREATIONDATE as ASSIGNMENTSUPERVISORPEOCREATIONDATE,
               ASSIGNMENTSUPERVISORPEOLASTUPDATEDATE as ASSIGNMENTSUPERVISORPEOLASTUPDATEDATE,
               ASSIGNMENTSUPERVISORPEOLASTUPDATEDBY as ASSIGNMENTSUPERVISORPEOLASTUPDATEDBY 
      from `chrome-genre-298014.sakra_stage.h_assignmentam_assignmentsupervisorpvo`
)

select * from h_assignmentam_assignmentsupervisorpvo
