with f_fingljrnlsetupcatam_journalcategorybpvo as ( 
      select 
               JRNLCATCONSOLIDATIONFLAG as JRNLCATCONSOLIDATIONFLAG,
               JRNLCATCREATEDBY as JRNLCATCREATEDBY,
               JRNLCATCREATIONDATE as JRNLCATCREATIONDATE,
               JRNLCATJECATEGORYKEY as JRNLCATJECATEGORYKEY,
               JECATEGORYNAME as JECATEGORYNAME,
               JRNLCATLASTUPDATEDATE as JRNLCATLASTUPDATEDATE,
               JRNLCATLASTUPDATELOGIN as JRNLCATLASTUPDATELOGIN,
               JRNLCATLASTUPDATEDBY as JRNLCATLASTUPDATEDBY,
               JRNLCATOBJECTVERSIONNUMBER as JRNLCATOBJECTVERSIONNUMBER,
               JRNLCATTRANSLATEDCREATEDBY as JRNLCATTRANSLATEDCREATEDBY,
               JRNLCATTRANSLATEDCREATIONDATE as JRNLCATTRANSLATEDCREATIONDATE,
               JRNLCATTRANSLATEDDESCRIPTION as JRNLCATTRANSLATEDDESCRIPTION,
               JRNLCATTRANSLATEDJECATEGORYNAME as JRNLCATTRANSLATEDJECATEGORYNAME,
               JRNLCATTRANSLATEDLANGUAGE as JRNLCATTRANSLATEDLANGUAGE,
               JRNLCATTRANSLATEDLASTUPDATEDATE as JRNLCATTRANSLATEDLASTUPDATEDATE,
               JRNLCATTRANSLATEDLASTUPDATELOGIN as JRNLCATTRANSLATEDLASTUPDATELOGIN,
               JRNLCATTRANSLATEDLASTUPDATEDBY as JRNLCATTRANSLATEDLASTUPDATEDBY,
               JRNLCATTRANSLATEDOBJECTVERSIONNUMBER as JRNLCATTRANSLATEDOBJECTVERSIONNUMBER,
               JRNLCATTRANSLATEDSOURCELANG as JRNLCATTRANSLATEDSOURCELANG,
               JRNLCATTRANSLATEDUSERJECATEGORYNAME as JRNLCATTRANSLATEDUSERJECATEGORYNAME,
      from 'chrome-genre-298014.sakra_stage.f_fingljrnlsetupcatam_journalcategorybpvo'
)

select * from f_fingljrnlsetupcatam_journalcategorybpvo
