with h_actionam_actionreasonspvo as ( 
      select 
               ACTIONREASONID as ACTIONREASONID,
               ACTIONREASONSPEOACTIONREASONCODE as ACTIONREASONSPEOACTIONREASONCODE,
               ACTIONREASONSPEOBUSINESSGROUPID as ACTIONREASONSPEOBUSINESSGROUPID,
               ACTIONREASONSPEOLASTUPDATELOGIN as ACTIONREASONSPEOLASTUPDATELOGIN,
               ACTIONREASONSPEOLASTUPDATEDBY as ACTIONREASONSPEOLASTUPDATEDBY,
               ACTIONREASONSPEOLASTUPDATEDATE as ACTIONREASONSPEOLASTUPDATEDATE,
               ACTIONREASONSPEOCREATEDBY as ACTIONREASONSPEOCREATEDBY,
               ACTIONREASONSPEOCREATIONDATE as ACTIONREASONSPEOCREATIONDATE,
      from 'chrome-genre-298014.sakra_stage.h_actionam_actionreasonspvo'
)

select * from h_actionam_actionreasonspvo
