with h_jobam_jobfamilypvo as ( 
      select 
               JOBFAMILYID as JOBFAMILYID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               JOBFAMILYPEOACTIVESTATUS as JOBFAMILYPEOACTIVESTATUS,
               JOBFAMILYPEOACTIONOCCURRENCEID as JOBFAMILYPEOACTIONOCCURRENCEID,
               JOBFAMILYPEOBUSINESSGROUPID as JOBFAMILYPEOBUSINESSGROUPID,
               JOBFAMILYPEOCREATEDBY as JOBFAMILYPEOCREATEDBY,
               JOBFAMILYPEOCREATIONDATE as JOBFAMILYPEOCREATIONDATE,
               JOBFAMILYPEOLASTUPDATEDATE as JOBFAMILYPEOLASTUPDATEDATE,
               JOBFAMILYPEOLASTUPDATELOGIN as JOBFAMILYPEOLASTUPDATELOGIN,
               JOBFAMILYPEOLASTUPDATEDBY as JOBFAMILYPEOLASTUPDATEDBY,
               JOBFAMILYPEOOBJECTVERSIONNUMBER as JOBFAMILYPEOOBJECTVERSIONNUMBER,
               JOBFAMILYCODE as JOBFAMILYCODE 
      from 'chrome-genre-298014.sakra_stage.h_jobam_jobfamilypvo'
)

select * from h_jobam_jobfamilypvo
