with h_actionam_actionoccurrencespvo as ( 
      select 
               ACTIONOCCURRENCEID as ACTIONOCCURRENCEID,
               ACTIONOCCURRENCESPEOACTIONID as ACTIONOCCURRENCESPEOACTIONID,
               ACTIONOCCURRENCESPEOACTIONREASONID as ACTIONOCCURRENCESPEOACTIONREASONID,
               ACTIONOCCURRENCESPEOCREATIONDATE as ACTIONOCCURRENCESPEOCREATIONDATE,
               ACTIONOCCURRENCESPEOCREATEDBY as ACTIONOCCURRENCESPEOCREATEDBY,
               ACTIONOCCURRENCESPEOLASTUPDATEDATE as ACTIONOCCURRENCESPEOLASTUPDATEDATE,
               ACTIONOCCURRENCESPEOLASTUPDATEDBY as ACTIONOCCURRENCESPEOLASTUPDATEDBY,
               ACTIONOCCURRENCESPEOLASTUPDATELOGIN as ACTIONOCCURRENCESPEOLASTUPDATELOGIN 
      from `chrome-genre-298014.sakra_stage.h_actionam_actionoccurrencespvo`
)

select * from h_actionam_actionoccurrencespvo
