with h_gradeam_salarybasispvo as ( 
      select 
               SALARYBASISID as SALARYBASISID,
               SALARYBASISPEOANNUALIZEDHOURS as SALARYBASISPEOANNUALIZEDHOURS,
               SALARYBASISPEOBUSINESSGROUPID as SALARYBASISPEOBUSINESSGROUPID,
               SALARYBASISPEOCOMPONENTUSAGE as SALARYBASISPEOCOMPONENTUSAGE,
               SALARYBASISPEOCREATEDBY as SALARYBASISPEOCREATEDBY,
               SALARYBASISPEOCREATIONDATE as SALARYBASISPEOCREATIONDATE,
               SALARYBASISPEOELEMENTTYPEID as SALARYBASISPEOELEMENTTYPEID,
               SALARYBASISPEOGRADEANNUALIZATIONFACTOR as SALARYBASISPEOGRADEANNUALIZATIONFACTOR,
               SALARYBASISPEOGRADERATEBASISCODE as SALARYBASISPEOGRADERATEBASISCODE,
               SALARYBASISPEOGRADERATEID as SALARYBASISPEOGRADERATEID,
               SALARYBASISPEOINPUTVALUEID as SALARYBASISPEOINPUTVALUEID,
               SALARYBASISPEOLASTUPDATEDATE as SALARYBASISPEOLASTUPDATEDATE,
               SALARYBASISPEOLASTUPDATEDBY as SALARYBASISPEOLASTUPDATEDBY,
               SALARYBASISPEOLEGALENTITYID as SALARYBASISPEOLEGALENTITYID,
               SALARYBASISPEONAME as SALARYBASISPEONAME,
               SALARYBASISPEOOBJECTVERSIONNUMBER as SALARYBASISPEOOBJECTVERSIONNUMBER,
               SALARYBASISPEOSALARYANNUALIZATIONFACTOR as SALARYBASISPEOSALARYANNUALIZATIONFACTOR,
               SALARYBASISPEOSALARYBASISCODE as SALARYBASISPEOSALARYBASISCODE 
      from `chrome-genre-298014.sakra_stage.h_gradeam_salarybasispvo`
)

select * from h_gradeam_salarybasispvo
