with h_personam_persondisabilitypvo as ( 
      select 
               DISABILITYID as DISABILITYID,
               EFFECTIVESTARTDATE as EFFECTIVESTARTDATE,
               EFFECTIVEENDDATE as EFFECTIVEENDDATE,
               PERSONDISABILITYPEOPERSONID as PERSONDISABILITYPEOPERSONID,
               PERSONDISABILITYPEOBUSINESSGROUPID as PERSONDISABILITYPEOBUSINESSGROUPID,
               PERSONDISABILITYPEOLEGISLATIONCODE as PERSONDISABILITYPEOLEGISLATIONCODE,
               PERSONDISABILITYPEOORGANIZATIONID as PERSONDISABILITYPEOORGANIZATIONID,
               PERSONDISABILITYPEOREGISTRATIONID as PERSONDISABILITYPEOREGISTRATIONID,
               PERSONDISABILITYPEOREGISTRATIONDATE as PERSONDISABILITYPEOREGISTRATIONDATE,
               PERSONDISABILITYPEOREGISTRATIONEXPDATE as PERSONDISABILITYPEOREGISTRATIONEXPDATE,
               PERSONDISABILITYPEOCATEGORY as PERSONDISABILITYPEOCATEGORY,
               PERSONDISABILITYPEODESCRIPTION as PERSONDISABILITYPEODESCRIPTION,
               PERSONDISABILITYPEODEGREE as PERSONDISABILITYPEODEGREE,
               PERSONDISABILITYPEOREASON as PERSONDISABILITYPEOREASON,
               PERSONDISABILITYPEOWORKRESTRICTION as PERSONDISABILITYPEOWORKRESTRICTION,
               PERSONDISABILITYPEOSTATUS as PERSONDISABILITYPEOSTATUS,
               PERSONDISABILITYPEOSELFDISCLOSEDTYPE as PERSONDISABILITYPEOSELFDISCLOSEDTYPE,
               PERSONDISABILITYPEODISCLOSUREDATE as PERSONDISABILITYPEODISCLOSUREDATE,
               PERSONDISABILITYPEOACCOMMODATIONREQUEST as PERSONDISABILITYPEOACCOMMODATIONREQUEST,
               PERSONDISABILITYPEOCREATIONDATE as PERSONDISABILITYPEOCREATIONDATE,
               PERSONDISABILITYPEOLASTUPDATEDATE as PERSONDISABILITYPEOLASTUPDATEDATE 
      from 'chrome-genre-298014.sakra_stage.h_personam_persondisabilitypvo'
)

select * from h_personam_persondisabilitypvo
