with h_actionam_actionspvo as ( 
      select 
               ACTIONID as ACTIONID,
               ACTIONSPEOACTIONTYPEID as ACTIONSPEOACTIONTYPEID,
               ACTIONSPEOBUSINESSGROUPID as ACTIONSPEOBUSINESSGROUPID,
               ACTIONSPEOACTIONCODE as ACTIONSPEOACTIONCODE,
               ACTIONSPEOACTIONTYPECODE as ACTIONSPEOACTIONTYPECODE,
               ACTIONSPEOACTINFORMATION1 as ACTIONSPEOACTINFORMATION1,
               ACTIONSPEOACTINFORMATION2 as ACTIONSPEOACTINFORMATION2,
               ACTIONSPEOLASTUPDATELOGIN as ACTIONSPEOLASTUPDATELOGIN,
               ACTIONSPEOCREATEDBY as ACTIONSPEOCREATEDBY,
               ACTIONSPEOCREATIONDATE as ACTIONSPEOCREATIONDATE,
               ACTIONSPEOLASTUPDATEDATE as ACTIONSPEOLASTUPDATEDATE,
               ACTIONSPEOLASTUPDATEDBY as ACTIONSPEOLASTUPDATEDBY 
      from 'chrome-genre-298014.sakra_stage.h_actionam_actionspvo'
)

select * from h_actionam_actionspvo
