with h_assignmentam_assignmentstatustypespvo as ( 
      select 
               ASSIGNMENTSTATUSTYPEID as ASSIGNMENTSTATUSTYPEID,
               ASSIGNMENTSTATUSTYPESPEOACTIVEFLAG as ASSIGNMENTSTATUSTYPESPEOACTIVEFLAG,
               ASSIGNMENTSTATUSTYPESPEOASSIGNMENTSTATUSCODE as ASSIGNMENTSTATUSTYPESPEOASSIGNMENTSTATUSCODE,
               ASSIGNMENTSTATUSTYPESPEOBUSINESSGROUPID as ASSIGNMENTSTATUSTYPESPEOBUSINESSGROUPID,
               ASSIGNMENTSTATUSTYPESPEOCREATEDBY as ASSIGNMENTSTATUSTYPESPEOCREATEDBY,
               ASSIGNMENTSTATUSTYPESPEOCREATIONDATE as ASSIGNMENTSTATUSTYPESPEOCREATIONDATE,
               ASSIGNMENTSTATUSTYPESPEOENDDATE as ASSIGNMENTSTATUSTYPESPEOENDDATE,
               ASSIGNMENTSTATUSTYPESPEOLASTUPDATEDATE as ASSIGNMENTSTATUSTYPESPEOLASTUPDATEDATE,
               ASSIGNMENTSTATUSTYPESPEOLASTUPDATELOGIN as ASSIGNMENTSTATUSTYPESPEOLASTUPDATELOGIN,
               ASSIGNMENTSTATUSTYPESPEOLASTUPDATEDBY as ASSIGNMENTSTATUSTYPESPEOLASTUPDATEDBY,
               ASSIGNMENTSTATUSTYPESPEOLEGISLATIONCODE as ASSIGNMENTSTATUSTYPESPEOLEGISLATIONCODE,
               ASSIGNMENTSTATUSTYPESPEOORIGASSIGNSTATUSTYPEID as ASSIGNMENTSTATUSTYPESPEOORIGASSIGNSTATUSTYPEID,
               ASSIGNMENTSTATUSTYPESPEOPAYSYSTEMSTATUS as ASSIGNMENTSTATUSTYPESPEOPAYSYSTEMSTATUS,
               ASSIGNMENTSTATUSTYPESPEOPERSYSTEMSTATUS as ASSIGNMENTSTATUSTYPESPEOPERSYSTEMSTATUS,
               ASSIGNMENTSTATUSTYPESPEOPRIMARYFLAG as ASSIGNMENTSTATUSTYPESPEOPRIMARYFLAG,
               ASSIGNMENTSTATUSTYPESPEOSTARTDATE as ASSIGNMENTSTATUSTYPESPEOSTARTDATE,
      from 'chrome-genre-298014.sakra_stage.h_assignmentam_assignmentstatustypespvo'
)

select * from h_assignmentam_assignmentstatustypespvo
